

str = """1Time Airline",\\N,"1T","RNX","NEXTIME","South Africa"
40-Mile Air",\\N,"Q5","MLA","MILE-AIR","United States"
Ansett Australia",\\N,"AN","AAA","ANSETT","Australia"
Abacus International",\\N,"1B","","","Singapore"
Aigle Azur",\\N,"ZI","AAF","AIGLE AZUR","France"
Aloha Airlines",\\N,"AQ","AAH","ALOHA","United States"
American Airlines",\\N,"AA","AAL","AMERICAN","United States"
Asiana Airlines",\\N,"OZ","AAR","ASIANA","Republic of Korea"
Askari Aviation",\\N,"4K","AAS","AL-AAS","Pakistan"
Afriqiyah Airways",\\N,"8U","AAW","AFRIQIYAH","Libya"
Allegiant Air",\\N,"G4","AAY","ALLEGIANT","United States"
ABSA - Aerolinhas Brasileiras",\\N,"M3","TUS","ABSA Cargo","Brazil"
Astral Aviation",\\N,"8V","ACP","ASTRAL CARGO","Kenya"
Air Tindi",\\N,"8T","","","Canadian Territories"
Ada Air",\\N,"ZY","ADE","ADA AIR","Albania"
Adria Airways",\\N,"JP","ADR","ADRIA","Slovenia"
Air Europa",\\N,"UX","AEA","EUROPA","Spain"
Aero Benin",\\N,"EM","AEB","AEROBEN","Benin"
Aegean Airlines",\\N,"A3","AEE","AEGEAN","Greece"
Air Europe",\\N,"PE","AEL","AIR EUROPE","Italy"
Alaska Central Express",\\N,"KO","AER","ACE AIR","United States"
ACES Colombia",\\N,"","AES","ACES","Colombia"
Astraeus",\\N,"5W","AEU","FLYSTAR","United Kingdom"
Aerosvit Airlines",\\N,"VV","AEW","AEROSVIT","Ukraine"
Air Italy",\\N,"I9","AEY","AIR ITALY","Italy"
Alliance Airlines",\\N,"QQ","UTY","UNITY","Australia"
Ariana Afghan Airlines",\\N,"FG","AFG","ARIANA","Afghanistan"
Aeroflot Russian Airlines",\\N,"SU","AFL","AEROFLOT","Russia"
Air Bosna",\\N,"JA","BON","AIR BOSNA","Bosnia and Herzegovina"
Air France",\\N,"AF","AFR","AIRFRANS","France"
Air Caledonie International",\\N,"SB","ACI","AIRCALIN","France"
Air Salone",\\N,"2O","","","Sierra Leone"
Air Cargo Carriers",\\N,"2Q","SNC","NIGHT CARGO","United States"
Air Namibia",\\N,"SW","NMB","NAMIBIA","Namibia"
Aerolitoral",\\N,"5D","SLI","COSTERA","Mexico"
Air Glaciers",\\N,"7T","AGV","AIR GLACIERS","Switzerland"
Aviogenex",\\N,"","AGX","GENEX","Serbia"
Aeroper",\\N,"PL","PLI","Aeroperu","Peru"
Atlas Blue",\\N,"8A","BMM","ATLAS BLUE","Morocco"
Azerbaijan Airlines",\\N,"J2","AHY","AZAL","Azerbaijan"
Avies",\\N,"U3","AIA","AVIES","Estonia"
Airblue",\\N,"ED","ABQ","PAKBLUE","Pakistan"
Airlift International",\\N,"","AIR","AIRLIFT","United States"
Air Berlin",\\N,"AB","BER","AIR BERLIN","Germany"
Air India Limited",\\N,"AI","AIC","AIRINDIA","India"
Air Bourbon",\\N,"ZB","BUB","BOURBON","Reunion"
Air Atlanta Icelandic",\\N,"CC","ABD","ATLANTA","Iceland"
Air Tahiti Nui",\\N,"TN","THT","TAHITI AIRLINES","France"
Arkia Israel Airlines",\\N,"IZ","AIZ","ARKIA","Israel"
Air Jamaica",\\N,"JM","AJM","JAMAICA","Jamaica"
Air One",\\N,"AP","ADH","HERON","Italy"
Air Sahara",\\N,"S2","RSH","SAHARA","India"
Air Malta",\\N,"KM","AMC","AIR MALTA","Malta"
Air Japan",\\N,"NQ","AJX","AIR JAPAN","Japan"
Air Korea Co. Ltd.",\\N,"","AKA","","Republic of Korea"
Air Kiribati",\\N,"4A","AKL","","Kiribati"
America West Airlines",\\N,"HP","AWE","CACTUS","United States"
Air Wisconsin",\\N,"ZW","AWI","AIR WISCONSIN","United States"
Tatarstan Airlines",\\N,"U9","TAK","TATARSTAN","Russia"
Allegheny Commuter Airlines",\\N,"","ALO","ALLEGHENY","United States"
Air Sunshine",\\N,"","RSI","AIR SUNSHINE","United States"
Air Libert",\\N,"VD","","","France"
Air Malawi",\\N,"QM","AML","MALAWI","Malawi"
Air Sicilia",\\N,"BM","","","Italy"
ATA Airlines",\\N,"","AMT","AMTRAN","United States"
Air Macau",\\N,"NX","AMU","AIR MACAO","Macao"
AMC Airlines",\\N,"","AMV","","Egypt"
Air Seychelles",\\N,"HM","SEY","SEYCHELLES","Seychelles"
AeroMéxico",\\N,"AM","AMX","AEROMEXICO","Mexico"
All Nippon Airways","ANA All Nippon Airways","NH","ANA","ALL NIPPON","Japan"
Air Nostrum",\\N,"YW","ANE","AIR NOSTRUM","Spain"
Air Niugini",\\N,"PX","ANG","NUIGINI","Papua New Guinea"
Air Arabia",\\N,"G9","ABY","ARABIA","United Arab Emirates"
Air Canada",\\N,"AC","ACA","AIR CANADA","Canada"
Air Baltic",\\N,"BT","BTI","AIRBALTIC","Latvia"
Air Nippon",\\N,"EL","ANK","ANK AIR","Japan"
Airnorth",\\N,"TL","ANO","TOPEND","Australia"
Air North Charter - Canada",\\N,"4N","ANT","AIR NORTH","Canada"
Air New Zealand",\\N,"NZ","ANZ","NEW ZEALAND","New Zealand"
Alitalia Express",\\N,"XM","SMX","ALIEXPRESS","Italy"
Aero Flight",\\N,"GV","ARF","Aero Fox","Germany"
Arrow Air",\\N,"JW","APW","BIG A","United States"
Aerocondor",\\N,"2B","ARD","AEROCONDOR","Portugal"
Aires",\\N,"4C","ARE"," Aerovias de Integracion Regional"," S.A."
Aerolineas Argentinas",\\N,"AR","ARG","ARGENTINA","Argentina"
Alaska Airlines",\\N,"AS","ASA"," Inc.","ALASKA"
Air Sinai",\\N,"4D","ASD","AIR SINAI","Egypt"
Atlantic Southeast Airlines",\\N,"EV","ASQ","ACEY","United States"
Astrakhan Airlines",\\N,"OB","ASZ","AIR ASTRAKHAN","Russia"
Air Tanzania",\\N,"TC","ATC","TANZANIA","Tanzania"
Air Burkina",\\N,"2J","VBW","BURKINA","Burkina Faso"
Airlines Of Tasmania",\\N,"FO","ATM","AIRTAS","Australia"
Air Saint Pierre",\\N,"PJ","SPM","","France"
Austrian Airlines",\\N,"OS","AUA","AUSTRIAN","Austria"
Air Southwest",\\N,"","WOW","SWALLOW","United Kingdom"
Augsburg Airways",\\N,"IQ","AUB","AUGSBURG-AIR","Germany"
ATUR",\\N,"","TUR","","Ecuador"
Abu Dhabi Amiri Flight",\\N,"MO","AUH","SULTAN","United Arab Emirates"
Aeroflot-Nord",\\N,"5N","AUL","DVINA","Russia"
Aurigny Air Services",\\N,"GR","AUR","AYLINE","United Kingdom"
Austral Lineas Aereas",\\N,"AU","AUT","AUSTRAL","Argentina"
Avianca - Aerovias Nacionales de Colombia",\\N,"AV","AVA"," S.A.","AVIANCA"
Air Vanuatu",\\N,"NF","AVN","AIR VAN","Vanuatu"
Air Bangladesh",\\N,"B9","BGD","AIR BANGLA","Bangladesh"
Air Mediterranee",\\N,"DR","BIE","MEDITERRANEE","France"
Air Moorea",\\N,"","TAH","AIR MOOREA","France"
Aeroline GmbH",\\N,"7E","AWU","SYLT-AIR","Germany"
Air Wales",\\N,"6G","AWW","RED DRAGON","United Kingdom"
Air Caraïbes",\\N,"TX","FWI","FRENCH WEST","France"
Air India Express",\\N,"IX","AXB","EXPRESS INDIA","India"
Air Exel",\\N,"XT","AXL","EXEL COMMUTER","Netherlands"
AirAsia","Air Asia","AK","AXM","ASIAN EXPRESS","Malaysia"
Atlant-Soyuz Airlines",\\N,"3G","AYZ","ATLANT-SOYUZ","Russia"
Alitalia",\\N,"AZ","AZA","ALITALIA","Italy"
Amaszonas",\\N,"Z8","AZN","","Bolivia"
Air Zimbabwe",\\N,"UM","AZW","AIR ZIMBABWE","Zimbabwe"
Aserca Airlines",\\N,"R7","OCA","AROSCA","Venezuela"
Rossiya-Russian Airlines","Pulkovo Aviation Enterprise","FV","SDM","PULKOVO","Russia"
American Eagle Airlines",\\N,"MQ","EGF","EAGLE FLIGHT","United States"
AD Aviation",\\N,"","VUE","FLIGHTVUE","United Kingdom"
Air Ivoire",\\N,"VU","VUN","AIRIVOIRE","Ivory Coast"
Air Botswana",\\N,"BP","BOT","BOTSWANA","Botswana"
Air Foyle",\\N,"GS","UPA","FOYLE","United Kingdom"
Air Tahiti",\\N,"VT","VTA","AIR TAHITI","French Polynesia"
Air VIA",\\N,"VL","VIM","","Bulgaria"
Africa West",\\N,"FK","WTA","WEST TOGO","Togo"
ATRAN Cargo Airlines",\\N,"V8","VAS","ATRAN","Russian Federation"
Air China",\\N,"CA","CCA","AIR CHINA","China"
Aero Condor Peru",\\N,"Q6","CDP","CONDOR-PERU","Peru"
Air Chathams",\\N,"CV","CVA","CHATHAM","New Zealand"
Air Marshall Islands",\\N,"CW","CWM","AIR MARSHALLS","Marshall Islands"
Access Air",\\N,"ZA","CYD","CYCLONE","United States"
Air Algerie",\\N,"AH","DAH","AIR ALGERIE","Algeria"
Adam Air",\\N,"KI","DHI","ADAM SKY","Indonesia"
Air Dolomiti",\\N,"EN","DLA","DOLOMOTI","Italy"
Aeroflot-Don",\\N,"D9","DNV","DONAVIA","Russia"
Air Madrid",\\N,"NM","DRD","ALADA AIR","Spain"
Aer Lingus",\\N,"EI","EIN","SHAMROCK","Ireland"
Air Finland",\\N,"OF","FIF","AIR FINLAND","Finland"
Airfix Aviation",\\N,"","FIX","AIRFIX","Finland"
Air Pacific",\\N,"FJ","FJI","PACIFIC","Fiji"
Atlantic Airways",\\N,"RC","FLI","FAROELINE","Faroe Islands"
Air Florida",\\N,"QH","FLZ","AIR FLORIDA","United States"
Air Iceland",\\N,"NY","FXI","FAXI","Iceland"
Air Philippines",\\N,"2P","GAP","ORIENT PACIFIC","Philippines"
Air Guinee Express",\\N,"2U","GIP","FUTURE EXPRESS","Guinea"
Air Greenland",\\N,"GL","GRL","GREENLAND","Denmark"
Atlas Air",\\N,"5Y","GTI","GIANT","United States"
Air Guyane",\\N,"GG","GUY","GREEN BIRD","French Guiana"
Air Bagan",\\N,"W9","JAB","AIR BAGAN","Myanmar"
Air Canada Jazz",\\N,"QK","JZA","JAZZ","Canada"
Atlasjet",\\N,"KK","KKK","ATLASJET","Turkey"
Air Koryo",\\N,"JS","KOR","AIR KORYO","Democratic People's Republic of Korea"
Air Astana",\\N,"KC","KZR","ASTANALINE","Kazakhstan"
Albanian Airlines",\\N,"LV","LBC","ALBANIAN","Albania"
Air Alfa",\\N,"","LFA","","Turkey"
Aerolane",\\N,"XL","LNE","LAN ECUADOR","Ecuador"
Atlantis European Airways",\\N,"TD","LUR","","Armenia"
Air Luxor",\\N,"LK","LXR","AIRLUXOR","Portugal"
Air Mauritius",\\N,"MK","MAU","AIRMAURITIUS","Mauritius"
Air Madagascar",\\N,"MD","MDG","AIR MADAGASCAR","Madagascar"
Air Moldova",\\N,"9U","MLD","AIR MOLDOVA","Moldova"
Air Plus Comet",\\N,"A7","MPD","RED COMET","Spain"
Astair",\\N,"8D","","","Russian Federation"
Aero Contractors",\\N,"AJ","NIG","AEROLINE","Nigeria"
Aeropelican Air Services",\\N,"OT","PEL","PELICAN","Australia"
Aer Arann",\\N,"RE","REA","AER ARANN","Ireland"
Air Austral",\\N,"UU","REU","REUNION","France"
Asian Spirit",\\N,"6K","RIT","ASIAN SPIRIT","Philippines"
Air Afrique",\\N,"RK","RKA","AIRAFRIC","Ivory Coast"
Airlinair",\\N,"A5","RLA","AIRLINAIR","France"
Aero Lanka",\\N,"QL","RLN","AERO LANKA","Sri Lanka"
Air Salone",\\N,"20","RNE","AIR SALONE","Sierra Leone"
Armavia",\\N,"U8","RNV","ARMAVIA","Armenia"
AeroRep",\\N,"P5","RPB","AEROREPUBLICA","Colombia"
Aero-Service",\\N,"BF","RSR","CONGOSERV","Republic of the Congo"
Aerosur",\\N,"5L","RSU","AEROSUR","Bolivia"
Aeronorte",\\N,"","RTE","LUZAVIA","Portugal"
Avient Aviation",\\N,"Z3","SMJ","AVAVIA","Zimbabwe"
Aircompany Yakutia",\\N,"R3","SYL","AIR YAKUTIA","Russia"
Aeromar",\\N,"VW","TAO","TRANS-AEROMAR","Mexico"
Arkefly",\\N,"OR","TFL","ARKEFLY","Netherlands"
Airlines PNG",\\N,"CG","TOK","BALUS","Papua New Guinea"
AirTran Airways",\\N,"FL","TRS","CITRUS","United States"
Air Transat",\\N,"TS","TSC","TRANSAT","Canada"
Avialeasing Aviation Company",\\N,"EC","TWN","TWINARROW","Uzbekistan"
Tyrolean Airways",\\N,"VO","TYR","TYROLEAN","Austria"
Aerolineas Galapagos (Aerogal)",\\N,"2K","GLG","AEROGAL","Ecuador"
Alrosa Mirny Air Enterprise",\\N,"6R","DRU","MIRNY","Russia"
British Airways",\\N,"BA","BAW","SPEEDBIRD","United Kingdom"
Biman Bangladesh Airlines",\\N,"BG","BBC","BANGLADESH","Bangladesh"
Belair Airlines",\\N,"4T","BHP","BELAIR","Switzerland"
Bahamasair",\\N,"UP","BHS","BAHAMAS","Bahamas"
Balkan Bulgarian Airlines",\\N,"LZ","","",""
British International Helicopters",\\N,"BS","BIH","BRINTEL","United Kingdom"
BF-Lento OY",\\N,"","BKF","BAKERFLIGHT","Finland"
Bangkok Airways",\\N,"PG","BKP","BANGKOK AIR","Thailand"
Blue1",\\N,"KF","BLF","BLUEFIN","Finland"
Baltic Airlines",\\N,"","BLL","BALTIC AIRLINES","Russia"
Bearskin Lake Air Service",\\N,"JV","BLS","BEARSKIN","Canada"
Bellview Airlines",\\N,"B3","BLV","BELLVIEW AIRLINES","Nigeria"
bmi","bmi British Midland","BD","BMA","MIDLAND","United Kingdom"
bmibaby",\\N,"WW","BMI","BABY","United Kingdom"
Bemidji Airlines",\\N,"CH","BMJ","BEMIDJI","United States"
British Midland Regional",\\N,"","BMR","","United Kingdom"
Blue Panorama Airlines",\\N,"BV","BPA","BLUE PANOROMA","Italy"
Budapest Aircraft Services/Manx2",\\N,"","BPS","BASE","Hungary"
Bering Air",\\N,"8E","BRG","BERING AIR","United States"
Brazilian Air Force",\\N,"","BRS","BRAZILIAN AIR FORCE","Brazil"
Belavia Belarusian Airlines",\\N,"B2","BRU","BELARUS AVIA","Belarus"
Metro Batavia",\\N,"7P","BTV","BATAVIA","Indonesia"
Berjaya Air",\\N,"J8","BVT","BERJAYA","Malaysia"
Blue Wings",\\N,"QW","BWG","BLUE WINGS","Germany"
Brit Air",\\N,"DB","BZH","BRITAIR","France"
Brussels Airlines","SN Brussels Airlines","SN","DAT","BEE-LINE","Belgium"
Binter Canarias",\\N,"NT","IBB","","Spain"
Blue Air",\\N,"0B","JOR","BLUE TRANSPORT","Romania"
British Mediterranean Airways",\\N,"KJ","LAJ","BEE MED","United Kingdom"
Bulgaria Air",\\N,"FB","LZB","FLYING BULGARIA","Bulgaria"
Barents AirLink",\\N,"8N","NKF","NORDFLIGHT","Sweden"
CAL Cargo Air Lines",\\N,"5C","ICL","CAL","Israel"
Calima Aviacion",\\N,"XG","CLI","CALIMA","Spain"
Canadian Airlines",\\N,"CP","CDN","CANADIAN","Canada"
Canadian North",\\N,"5T","MPE","EMPRESS","Canada"
Cape Air",\\N,"9K","KAP","CAIR","United States"
Caribbean Airlines",\\N,"BW","BWA","CARIBBEAN AIRLINES","Trinidad and Tobago"
Carpatair",\\N,"V3","KRP","CARPATAIR","Romania"
Caspian Airlines",\\N,"RV","CPN","CASPIAN","Iran"
Cathay Pacific",\\N,"CX","CPA","CATHAY","Hong Kong SAR of China"
Cayman Airways",\\N,"KX","CAY","CAYMAN","Cayman Islands"
Cebu Pacific",\\N,"5J","CEB","CEBU AIR","Philippines"
Central Connect Airlines",\\N,"","CCG","","Czech Republic"
Centralwings",\\N,"C0","CLW","CENTRALWINGS","Poland"
Charter Air",\\N,"","CHW","CHARTER WIEN","Austria"
Chautauqua Airlines",\\N,"RP","CHQ","CHAUTAUQUA","United States"
China Airlines",\\N,"CI","CAL","DYNASTY","Taiwan"
China Eastern Airlines",\\N,"MU","CES","CHINA EASTERN","China"
China Southern Airlines",\\N,"CZ","CSN","CHINA SOUTHERN","China"
China United Airlines",\\N,"HR","CUA","LIANHANG","China"
Yunnan Airlines",\\N,"3Q","CYH","YUNNAN","China"
Cimber Air",\\N,"QI","CIM","CIMBER","Denmark"
Cirrus Airlines",\\N,"C9","RUS","CIRRUS AIR","Germany"
City Airline",\\N,"CF","SDR","SWEDESTAR","Sweden"
City Connexion Airlines",\\N,"G3","CIX","CONNEXION","Burundi"
CityJet",\\N,"WX","BCY","CITY-IRELAND","Ireland"
BA CityFlyer",\\N,"CJ","CFE","FLYER","United Kingdom"
Click Airways",\\N,"","CGK","CLICK AIR","Kyrgyzstan"
Coastal Air",\\N,"DQ","","U.S. Virgin Islands","United States"
Colgan Air",\\N,"9L","CJC","COLGAN","United States"
Comair",\\N,"OH","COM","COMAIR","United States"
Comair",\\N,"MN","CAW","COMMERCIAL","South Africa"
CommutAir",\\N,"C5","UCA","COMMUTAIR","United States"
Comores Airlines",\\N,"KR","CWK","CONTICOM","Comoros"
Compass Airlines",\\N,"CP","CPZ","Compass Rose","United States"
Condor Flugdienst",\\N,"DE","CFG","CONDOR","Germany"
Consorcio Aviaxsa",\\N,"6A","CHP","AVIACSA","Mexico"
Contact Air","Contactair","C3","KIS","CONTACTAIR","Germany"
Continental Airlines",\\N,"CO","COA","CONTINENTAL","United States"
Continental Express",\\N,"CO","","JETLINK","United States"
Continental Micronesia",\\N,"CS","CMI","AIR MIKE","United States"
Conviasa",\\N,"V0","VCV","CONVIASA","Venezuela"
Copa Airlines",\\N,"CM","CMP","COPA","Panama"
Copterline",\\N,"","AAQ","COPTERLINE","Finland"
Corendon Airlines",\\N,"","CAI","CORENDON","Turkey"
Corsairfly",\\N,"SS","CRL","CORSAIR","France"
Corse-Mediterranee",\\N,"XK","CCM","CORSICA","France"
Crest Aviation",\\N,"","CAN","CREST","United Kingdom"
Croatia Airlines",\\N,"OU","CTN","CROATIA","Croatia"
Crown Airways",\\N,"","CRO","CROWN AIRWAYS","United States"
Cubana de Aviación",\\N,"CU","CUB","CUBANA","Cuba"
Cyprus Airways",\\N,"CY","CYP","CYPRUS","Cyprus"
Cyprus Turkish Airlines",\\N,"YK","","","Turkey"
Czech Airlines","CSA Czech Airlines","OK","CSA","CSA-LINES","Czech Republic"
DAT Danish Air Transport",\\N,"DX","DTR","DANISH","Denmark"
Daallo Airlines",\\N,"D3","DAO","DALO AIRLINES","Djibouti"
Dalavia",\\N,"H8","KHB","DALAVIA","Russia"
Darwin Airline",\\N,"0D","DWT","DARWIN","Switzerland"
Delta Aerotaxi",\\N,"","DEA","JET SERVICE","Italy"
Delta Air Lines",\\N,"DL","DAL","DELTA","United States"
Denim Air",\\N,"","DNM","DENIM","Netherlands"
Deutsche Bahn",\\N,"2A","","","Germany"
Djibouti Airlines",\\N,"D8","DJB","DJIBOUTI AIR","Djibouti"
Dniproavia",\\N,"","UDN","DNIEPRO","Ukraine"
Dominicana de Aviaci",\\N,"DO","DOA","DOMINICANA","Dominican Republic"
Domodedovo Airlines",\\N,"E3","DMO","DOMODEDOVO","Russia"
DonbassAero",\\N,"5D","UDC","DONBASS AERO","Ukraine"
Dragonair",\\N,"KA","HDA"," Hong Kong Dragon Airlines","DRAGON"
Druk Air",\\N,"KB","DRK","ROYAL BHUTAN","Bhutan"
Dubrovnik Air",\\N,"","DBK","SEAGULL","Croatia"
Dutch Antilles Express",\\N,"","DNL","DUTCH ANTILLES","Netherlands Antilles"
dba",\\N,"DI","BAG","SPEEDWAY","Germany"
EVA Air",\\N,"BR","EVA","EVA","Taiwan"
Eagle Air",\\N,"H7","","","Uganda"
East African",\\N,"QU","UGX","CRANE","Uganda"
Eastern Airways",\\N,"T3","EZE","EASTFLIGHT","United Kingdom"
Eastland Air",\\N,"DK","ELA","","Australia"
Ecuavia",\\N,"","ECU","ECUAVIA","Ecuador"
Edelweiss Air",\\N,"WK","EDW","EDELWEISS","Switzerland"
Egyptair",\\N,"MS","MSR","EGYPTAIR","Egypt"
El Al Israel Airlines",\\N,"LY","ELY","ELAL","Israel"
El-Buraq Air Transport",\\N,"UZ","BRQ","BURAQAIR","Libya"
Emirates","Emirates Airlines","EK","UAE","EMIRATES","United Arab Emirates"
Empresa Ecuatoriana De Aviacion",\\N,"EU","EEA","ECUATORIANA","Ecuador"
Eritrean Airlines",\\N,"B8","ERT","ERITREAN","Eritrea"
Estonian Air",\\N,"OV","ELL","ESTONIAN","Estonia"
Ethiopian Airlines",\\N,"ET","ETH","ETHIOPIAN","Ethiopia"
Etihad Airways",\\N,"EY","ETD","ETIHAD","United Arab Emirates"
Euro Exec Express",\\N,"RZ","","","Sweden"
Eurocypria Airlines",\\N,"UI","ECA","EUROCYPRIA","Cyprus"
Eurofly Service",\\N,"GJ","EEU","EUROFLY","Italy"
Eurolot",\\N,"K2","ELO","EUROLOT","Poland"
European Air Express",\\N,"EA","EAL","STAR WING","Germany"
Eurowings",\\N,"EW","EWG","EUROWINGS","Germany"
Evergreen International Airlines",\\N,"EZ","EIA","EVERGREEN","United States"
Excel Airways",\\N,"JN","XLA","EXPO","United Kingdom"
Excel Charter",\\N,"","XEL","HELI EXCEL","United Kingdom"
Express One International",\\N,"EO","LHN","LONGHORN","United States"
ExpressJet",\\N,"XE","BTA","JET LINK","United States"
easyJet","EasyJet Airline","U2","EZY","EASY","United Kingdom"
Far Eastern Air Transport",\\N,"EF","EFA","Far Eastern","Taiwan"
Finnair",\\N,"AY","FIN","FINNAIR","Finland"
Finncomm Airlines",\\N,"FC","WBA","WESTBIRD","Finland"
Firefly",\\N,"FY","FFM","FIREFLY","Malaysia"
First Air",\\N,"7F","FAB","","Canada"
First Choice Airways",\\N,"DP","FCA","JETSET","United Kingdom"
Flightline",\\N,"B5","FLT","FLIGHTLINE","United Kingdom"
Florida West International Airways",\\N,"RF","FWL","FLO WEST","United States"
AirAsia X","FlyAsianXpress","D7","XAX","XANADU","Malaysia"
FlyLal",\\N,"TE","LIL","LITHUANIA AIR","Lithuania"
FlyNordic",\\N,"LF","NDC","NORDIC","Sweden"
Flybaboo",\\N,"F7","BBO","BABOO","Switzerland"
Flybe",\\N,"BE","BEE","JERSEY","United Kingdom"
Flyglobespan",\\N,"B4","GSM","GLOBESPAN","United Kingdom"
Flyhy Cargo Airlines",\\N,"","FYH","FLY HIGH","Thailand"
Formosa Airlines",\\N,"VY","FOS","","Taiwan"
Freedom Air",\\N,"FP","FRE","FREEDOM","United States"
Freedom Airlines",\\N,"","FRL","FREEDOM AIR","United States"
Frontier Airlines",\\N,"F9","FFT","FRONTIER FLIGHT","United States"
Frontier Flying Service",\\N,"2F","FTA","FRONTIER-AIR","United States"
GB Airways",\\N,"GT","GBL","GEEBEE AIRWAYS","United Kingdom"
Garuda Indonesia",\\N,"GA","GIA","INDONESIA","Indonesia"
Gazpromavia",\\N,"4G","GZP","GAZPROMAVIA","Russia"
Georgian Airways",\\N,"A9","TGZ","TAMAZI","Georgia"
Georgian National Airlines",\\N,"QB","GFG","NATIONAL","Georgia"
Germania",\\N,"ST","GMI","GERMANIA","Germany"
Germanwings",\\N,"4U","GWI","GERMAN WINGS","Germany"
Ghana International Airlines",\\N,"G0","GHB","GHANA AIRLINES","Ghana"
Go Air",\\N,"G8","GOW","GOAIR","India"
GoJet Airlines",\\N,"G7","GJS","GATEWAY","United States"
Gol Transportes Aéreos",\\N,"G3","GLO","GOL TRANSPORTE","Brazil"
Golden Air",\\N,"DC","GAO","GOLDEN","Sweden"
Great Lakes Airlines",\\N,"ZK","GLA","LAKES AIR","United States"
Grupo TACA","TACA","TA","TAT","TACA-COSTARICA","Costa Rica"
Gulf Air",\\N,"","GFA","GULF AIR","Oman"
Gulf Air Bahrain",\\N,"GF","GBA","GULF BAHRAIN","Bahrain"
Gulfstream International Airlines",\\N,"","GFT","GULF FLIGHT","United States"
Hageland Aviation Services",\\N,"H6","HAG","HAGELAND","United States"
Hainan Airlines",\\N,"HU","CHH","HAINAN","China"
Haiti Ambassador Airlines",\\N,"2T","HAM","","Haiti"
Hamburg International",\\N,"4R","HHI","HAMBURG JET","Germany"
TUIfly",\\N,"X3","HLX","YELLOW CAB","Germany"
Hapagfly",\\N,"HF","HLF","HAPAG LLOYD","Germany"
Hawaiian Airlines",\\N,"HA","HAL","HAWAIIAN","United States"
Hawkair",\\N,"BH","","","Canada"
Heli France",\\N,"8H","HFR","HELIFRANCE","France"
Helijet",\\N,"JB","JBA","HELIJET","Canada"
Hellas Jet",\\N,"T4","HEJ","HELLAS JET","Greece"
Hello",\\N,"HW","FHE","FLYHELLO","Switzerland"
Helvetic Airways",\\N,"2L","OAW","HELVETIC","Switzerland"
Hex'Air",\\N,"UD","HER","HEX AIRLINE","France"
Highland Airways",\\N,"","HWY","HIWAY","United Kingdom"
Hokkaido International Airlines",\\N,"HD","ADO","AIR DO","Japan"
Hong Kong Airlines",\\N,"HX","CRK","BAUHINIA","Hong Kong SAR of China"
Hong Kong Express Airways",\\N,"UO","HKE","HONGKONG SHUTTLE","Hong Kong SAR of China"
Horizon Air","Horizon Airlines","QX","QXE","HORIZON AIR","United States"
Horizon Airlines",\\N,"BN","HZA","","Australia"
Iberia Airlines",\\N,"IB","IBE","IBERIA","Spain"
Iberworld",\\N,"TY","IWD","","Spain"
Ibex Airlines",\\N,"FW","IBX","IBEX","Japan"
Icar Air",\\N,"","RAC","TUZLA AIR","Bosnia and Herzegovina"
Icelandair",\\N,"FI","ICE","ICEAIR","Iceland"
Imair Airlines",\\N,"IK","ITX","IMPROTEX","Azerbaijan"
IndiGo Airlines",\\N,"6E","IGO","IFLY","India"
Indian Airlines",\\N,"IC","IAC","INDAIR","India"
Indigo",\\N,"I9","IBU","INDIGO BLUE","United States"
Indonesia AirAsia",\\N,"QZ","AWQ","WAGON AIR","Indonesia"
Indonesian Airlines",\\N,"IO","IAA","INDO LINES","Indonesia"
Interair South Africa",\\N,"D6","ILN","INLINE","South Africa"
Interavia Airlines",\\N,"ZA","SUW","ASTAIR","Russia"
Interlink Airlines",\\N,"ID","ITK","INTERLINK","South Africa"
Intersky",\\N,"3L","ISK","INTERSKY","Austria"
Iran Air",\\N,"IR","IRA","IRANAIR","Iran"
Iran Aseman Airlines",\\N,"EP","IRC","","Iran"
Iraqi Airways",\\N,"IA","IAW","IRAQI","Iraq"
Island Airlines",\\N,"IS","","","United States"
Cargo Plus Aviation",\\N,"8L","CGP","","United Arab Emirates"
Islas Airways",\\N,"IF","ISW","PINTADERA","Spain"
Islena De Inversiones",\\N,"WC","ISV","","Honduras"
Israir",\\N,"6H","ISR","ISRAIR","Israel"
Itek Air",\\N,"GI","IKA","ITEK-AIR","Kyrgyzstan"
JAL Express",\\N,"JC","JEX","JANEX","Japan"
JALways",\\N,"JO","JAZ","JALWAYS","Japan"
Japan Airlines","JAL Japan Airlines","JL","JAL","JAPANAIR","Japan"
Japan Airlines Domestic",\\N,"JL","JAL","J-BIRD","Japan"
Japan Asia Airways",\\N,"EG","JAA","ASIA","Japan"
Japan Transocean Air",\\N,"NU","JTA","JAI OCEAN","Japan"
Jazeera Airways",\\N,"J9","JZR","JAZEERA","Kuwait"
Jeju Air",\\N,"7C","JJA","JEJU AIR","Republic of Korea"
Jet Airways",\\N,"9W","JAI","JET AIRWAYS","India"
Jet Airways",\\N,"QJ","","","United States"
Jetstar Asia Airways",\\N,"3K","JSA","JETSTAR ASIA","Singapore"
Jet2.com",\\N,"LS","EXS","CHANNEX","United Kingdom"
Jet4You","","8J","JFU","ARGAN","Morocco"
JetBlue Airways",\\N,"B6","JBU","JETBLUE","United States"
Jetairfly",\\N,"JF","JAF","BEAUTY","Belgium"
Jetflite",\\N,"","JEF","JETFLITE","Finland"
Jetstar Airways",\\N,"JQ","JST","JETSTAR","Australia"
Juneyao Airlines",\\N,"HO","DKH","JUNEYAO AIRLINES","China"
KD Avia",\\N,"KD","KNI","KALININGRAD AIR","Russia"
KLM Cityhopper",\\N,"WA","KLC","CITY","Netherlands"
KLM Royal Dutch Airlines",\\N,"KL","KLM","KLM","Netherlands"
Kam Air",\\N,"RQ","KMF","KAMGAR","Afghanistan"
Kavminvodyavia",\\N,"KV","MVD","AIR MINVODY","Russia"
Kendell Airlines",\\N,"","KDA","KENDELL","Australia"
Kenmore Air",\\N,"M5","KEN","KENMORE","United States"
Kenya Airways",\\N,"KQ","KQA","KENYA","Kenya"
Kingfisher Airlines",\\N,"IT","KFR","KINGFISHER","India"
Kish Air",\\N,"Y9","IRK","KISHAIR","Iran"
Kogalymavia Air Company",\\N,"7K","KGL","KOGALYM","Russia"
Korean Air",\\N,"KE","KAL","KOREANAIR","Republic of Korea"
Kosmos",\\N,"","KSM","KOSMOS","Russia"
Krasnojarsky Airlines",\\N,"7B","KJC","KRASNOJARSKY AIR","Russia"
Kuban Airlines",\\N,"GW","KIL","AIR KUBAN","Russia"
Kuwait Airways",\\N,"KU","KAC","KUWAITI","Kuwait"
Kuzu Airlines Cargo",\\N,"GO","KZU","KUZU CARGO","Turkey"
LACSA",\\N,"LR","LRC","LACSA","Costa Rica"
LAN Airlines",\\N,"LA","LAN","LAN","Chile"
LAN Argentina",\\N,"4M","DSM","LAN AR","Argentina"
LAN Express",\\N,"LU","LXP","LANEX","Chile"
LAN Peru",\\N,"LP","LPE","LANPERU","Peru"
LOT Polish Airlines",\\N,"LO","LOT","POLLOT","Poland"
LTE International Airways",\\N,"XO","LTE","FUN JET","Spain"
LTU Austria",\\N,"L3","LTO","BILLA TRANSPORT","Austria"
Lao Airlines",\\N,"QV","LAO","LAO","Lao Peoples Democratic Republic"
LatCharter",\\N,"","LTC","LATCHARTER","Latvia"
Lauda Air",\\N,"NG","LDA","LAUDA AIR","Austria"
Leeward Islands Air Transport",\\N,"LI","LIA","LIAT","Antigua and Barbuda"
Libyan Arab Airlines",\\N,"LN","LAA","LIBAIR","Libya"
Linhas A",\\N,"LM","LAM","MOZAMBIQUE","Mozambique"
Lion Mentari Airlines",\\N,"JT","LNI","LION INTER","Indonesia"
Luftfahrtgesellschaft Walter",\\N,"HE","LGW","WALTER","Germany"
Lufthansa",\\N,"LH","DLH","LUFTHANSA","Germany"
Lufthansa Cargo",\\N,"LH","GEC","LUFTHANSA CARGO","Germany"
Lufthansa CityLine",\\N,"CL","CLH","HANSALINE","Germany"
Lufttransport",\\N,"L5","LTR","LUFT TRANSPORT","Norway"
Luxair",\\N,"LG","LGL","LUXAIR","Luxembourg"
L",\\N,"MJ","LPR","LAPA","Argentina"
MasAir",\\N,"M7","MAA","MAS CARGA","Mexico"
MAT Macedonian Airlines",\\N,"IN","MAK","MAKAVIO","Macedonia"
MIAT Mongolian Airlines",\\N,"OM","MGL","MONGOL AIR","Mongolia"
MNG Airlines",\\N,"MB","MNB","BLACK SEA","Turkey"
Macair Airlines",\\N,"CC","MCK","","Australia"
Maersk",\\N,"DM","","","Denmark"
Mahan Air",\\N,"W5","IRM","MAHAN AIR","Iran"
Malaysia Airlines",\\N,"MH","MAS","MALAYSIAN","Malaysia"
Malmo Aviation",\\N,"","SCW","SCANWING","Sweden"
Malmö Aviation",\\N,"TF","SCW","Scanwings","Sweden"
Malta Air Charter",\\N,"R5","MAC","MALTA CHARTER","Malta"
Malév",\\N,"MA","MAH","MALEV","Hungary"
Mandala Airlines",\\N,"RI","MDL","MANDALA","Indonesia"
Mandarin Airlines",\\N,"AE","MDA","Mandarin","Taiwan"
Mango",\\N,"JE","MNO","TULCA","South Africa"
Martinair",\\N,"MP","MPH","MARTINAIR","Netherlands"
Maxair",\\N,"8M","MXL","MAXAIR","Sweden"
Maya Island Air",\\N,"MW","MYD","MYLAND","Belize"
Meridiana",\\N,"IG","ISS","MERAIR","Italy"
Merpati Nusantara Airlines",\\N,"MZ","MNA","MERPATI","Indonesia"
Mesa Airlines",\\N,"YV","ASH","AIR SHUTTLE","United States"
Mesaba Airlines",\\N,"XJ","MES","MESABA","United States"
Mexicana de Aviaci",\\N,"MX","MXA","MEXICANA","Mexico"
Middle East Airlines",\\N,"ME","MEA","CEDAR JET","Lebanon"
Midway Airlines",\\N,"JI","MDW","MIDWAY","United States"
Midwest Airlines",\\N,"YX","MEP","","United States"
Midwest Airlines (Egypt)",\\N,"MY","MWA","","Egypt"
Moldavian Airlines",\\N,"2M","MDV","MOLDAVIAN","Moldova"
Monarch Airlines",\\N,"ZB","MON","MONARCH","United Kingdom"
Myway Airlines",\\N,"8I","","","Italy"
Montenegro Airlines",\\N,"YM","MGX","MONTAIR","Montenegro"
Morningstar Air Express",\\N,"","MAL","MORNINGSTAR","Canada"
Moskovia Airlines",\\N,"3R","GAI","GROMOV AIRLINE","Russia"
Motor Sich",\\N,"M9","MSI","MOTOR SICH","Ukraine"
MyTravel Airways",\\N,"VZ","MYT","KESTREL","United Kingdom"
Myanma Airways",\\N,"UB","UBA","UNIONAIR","Myanmar"
Myanmar Airways International",\\N,"8M","MMM","assignment postponed","Myanmar"
Myflug",\\N,"","MYA","MYFLUG","Iceland"
Nasair",\\N,"UE","NAS","NASAIRWAYS","Eritrea"
National Jet Systems",\\N,"NC","NJS","NATIONAL JET","Australia"
Nationwide Airlines",\\N,"CE","NTW","NATIONWIDE","South Africa"
Nauru Air Corporation",\\N,"ON","RON","AIR NAURU","Nauru"
Nepal Airlines",\\N,"RA","RNA","ROYAL NEPAL","Nepal"
NetJets",\\N,"1I","EJA","EXECJET","United States"
New England Airlines",\\N,"EJ","NEA","NEW ENGLAND","United States"
NextJet",\\N,"2N","NTJ","NEXTJET","Sweden"
Niki",\\N,"HG","NLY","FLYNIKI","Austria"
Nok Air",\\N,"DD","NOK","NOK AIR","Thailand"
Norfolk County Flight College",\\N,"","NCF","COUNTY","United Kingdom"
North American Airlines",\\N,"","NTM","NORTHAM","Canada"
North American Charters",\\N,"","HMR","HAMMER","Canada"
Northern Dene Airways",\\N,"U7","","","Canada"
Northwest Airlines",\\N,"NW","NWA","NORTHWEST","United States"
Northwestern Air",\\N,"J3","PLR","POLARIS","Canada"
Norwegian Air Shuttle",\\N,"DY","NAX","NOR SHUTTLE","Norway"
Norwegian Aviation College",\\N,"","TFN","SPRIT","Norway"
Nouvel Air Tunisie",\\N,"BJ","LBT","NOUVELAIR","Tunisia"
Novair",\\N,"1I","NVR","NAVIGATOR","Sweden"
Nas Air",\\N,"XY","KNE","NAS EXPRESS","Saudi Arabia"
Oasis Hong Kong Airlines",\\N,"O8","OHK","OASIS","Hong Kong"
Ocean Air",\\N,"","BCN","BLUE OCEAN","Mauritania"
Oceanair",\\N,"O6","ONE","OCEANAIR","Brazil"
Oceanic Airlines",\\N,"O2","","","Guinea"
Olympic Airlines",\\N,"OA","OAL","OLYMPIC","Greece"
Oman Air",\\N,"WY","OMA","OMAN AIR","Oman"
Omni Air International",\\N,"OY","OAE","OMNI-EXPRESS","United States"
One Two Go Airlines",\\N,"","OTG","THAI EXPRESS","Thailand"
Onur Air",\\N,"8Q","OHY","ONUR AIR","Turkey"
Orenburg Airlines",\\N,"R2","ORB","ORENBURG","Russia"
Orient Thai Airlines",\\N,"OX","OEA","ORIENT THAI","Thailand"
Origin Pacific Airways",\\N,"QO","OGN","ORIGIN","New Zealand"
Ostfriesische Lufttransport",\\N,"OL","OLT","OLTRA","Germany"
Overland Airways",\\N,"OJ","OLA","OVERLAND","Nigeria"
Ozjet Airlines",\\N,"O7","OZJ","AUSJET","Australia"
PAN Air",\\N,"PV","PNR","SKYJET","Spain"
PB Air",\\N,"9Q","PBA","PEEBEE AIR","Thailand"
PLUNA",\\N,"PU","PUA","PLUNA","Uruguay"
PMTair",\\N,"U4","PMT","MULTITRADE","Cambodia"
Jetstar Pacific","Pacific Airlines","BL","PIC","PACIFIC AIRLINES","Vietnam"
Pacific Coastal Airline",\\N,"8P","PCO","PASCO","Canada"
Pacific East Asia Cargo Airlines",\\N,"Q8","PEC","PAC-EAST CARGO","Philippines"
Pacific Island Aviation",\\N,"","PSA","PACIFIC ISLE","United States"
Pacific Wings",\\N,"LW","NMI","TSUNAMI","United States"
Pakistan International Airlines","PIA Pakistan International","PK","PIA","PAKISTAN","Pakistan"
Paramount Airways",\\N,"I7","PMW","PARAWAY","India"
Passaredo Transportes Aereos",\\N,"","PTB","PASSAREDO","Brazil"
Pegasus Airlines",\\N,"PC","PGT","SUNTURK","Turkey"
Peninsula Airways",\\N,"KS","PEN","PENINSULA","United States"
Philippine Airlines",\\N,"PR","PAL","PHILIPPINE","Philippines"
Piedmont Airlines (1948-1989)",\\N,"PI","PDT","PIEDMONT","United States"
Pinnacle Airlines",\\N,"9E","FLG","FLAGSHIP","United States"
Polet",\\N,"","POT","POLET","Russia"
Polynesian Airlines",\\N,"PH","PAO","POLYNESIAN","Samoa"
Porter Airlines",\\N,"PD","POE","PORTER AIR","Canada"
Portugalia",\\N,"NI","PGA","PORTUGALIA","Portugal"
Potomac Air",\\N,"BK","PDC","DISTRICT","United States"
Precision Air",\\N,"PW","PRF","PRECISION AIR","Tanzania"
Privatair",\\N,"","PTI","PRIVATAIR","Switzerland"
Proflight Commuter Services",\\N,"P0","","","Zambia"
Qantas","Qantas Airways","QF","QFA","QANTAS","Australia"
Qatar Airways",\\N,"QR","QTR","QATARI","Qatar"
RACSA",\\N,"R6","","","Guatemala"
Kinloss Flying Training Unit",\\N,"","KIN","KINLOSS","United Kingdom"
Regional Airlines",\\N,"FN","","","Morocco"
Regional Express",\\N,"ZL","RXA","REX","Australia"
Republic Airlines",\\N,"RW","RPA","BRICKYARD","United States"
Republic Express Airlines",\\N,"RH","RPH","PUBLIC EXPRESS","Indonesia"
Rossiya",\\N,"R4","","","Russia"
Air Rarotonga",\\N,"GZ","RAR","","Cook Islands"
Royal Air Maroc",\\N,"AT","RAM","ROYALAIR MAROC","Morocco"
Royal Brunei Airlines",\\N,"BI","RBA","BRUNEI","Brunei"
Royal Jordanian",\\N,"RJ","RJA","JORDANIAN","Jordan"
Royal Nepal Airlines",\\N,"RA","RNA","ROYAL NEPAL","Nepal"
Royal Phnom Penh Airways",\\N,"","PPW","PHNOM-PENH AIR","Cambodia"
Rusline",\\N,"","RLU","RUSLINE AIR","Russia"
Rwandair Express",\\N,"WB","RWD","RWANDAIR","Rwanda"
Ryan Air Services",\\N,"","RYA","RYAN AIR","United States"
Ryan International Airlines",\\N,"RD","RYN","RYAN INTERNATIONAL","United States"
Ryanair",\\N,"FR","RYR","RYANAIR","Ireland"
Régional",\\N,"YS","RAE","REGIONAL EUROPE","France"
SATA International",\\N,"S4","RZO","AIR AZORES","Portugal"
South African Airways","SAA South African Airways","SA","SAA","SPRINGBOK","South Africa"
Shaheen Air International",\\N,"NL","SAI","SHAHEEN AIR","Pakistan"
Scandinavian Airlines System","SAS Scandinavian Airlines","SK","SAS","SCANDINAVIAN","Sweden"
ScotAirways",\\N,"","SAY","SUCKLING","United Kingdom"
S7 Airlines","Sibir Airlines","S7","SBI","SIBERIAN AIRLINES","Russia"
Seaborne Airlines",\\N,"BB","SBS","SEABORNE","United States"
Scenic Airlines",\\N,"","SCE","SCENIC","United States"
SriLankan Airlines",\\N,"UL","ALK","SRILANKAN","Sri Lanka"
Sun Country Airlines",\\N,"SY","SCX","SUN COUNTRY","United States"
Southeast Air",\\N,"","SEA","SOUTHEAST AIR","United States"
Sky Express",\\N,"G3","SEH","AIR CRETE","Greece"
Spicejet",\\N,"SG","SEJ","SPICEJET","India"
Star Flyer",\\N,"7G","SFJ","STARFLYER","Japan"
Skagway Air Service",\\N,"N5","SGY","SKAGWAY AIR","United States"
Sahara Airlines",\\N,"","SHD","","Algeria"
SATA Air Acores",\\N,"SP","SAT","SATA","Portugal"
Singapore Airlines",\\N,"SQ","SIA","SINGAPORE","Singapore"
Sibaviatrans",\\N,"5M","SIB","SIBAVIA","Russia"
Skynet Airlines",\\N,"SI","SIH","BLUEJET","Ireland"
Sriwijaya Air",\\N,"SJ","SJY","SRIWIJAYA","Indonesia"
Sama Airlines",\\N,"ZS","SMY","NAJIM","Saudi Arabia"
Singapore Airlines Cargo",\\N,"SQ","SQC","SINGCARGO","Singapore"
Siem Reap Airways",\\N,"FT","SRH","SIEMREAP AIR","Cambodia"
South East Asian Airlines",\\N,"DG","SRQ","SEAIR","Philippines"
Skyservice Airlines",\\N,"5G","SSV","SKYTOUR","Canada"
Servicios de Transportes A",\\N,"FS","STU","FUEGUINO","Argentina"
Sudan Airways",\\N,"SD","SUD","SUDANAIR","Sudan"
Saudi Arabian Airlines",\\N,"SV","SVA","SAUDIA","Saudi Arabia"
Southwest Airlines",\\N,"WN","SWA","SOUTHWEST","United States"
Southern Winds Airlines",\\N,"A4","SWD","SOUTHERN WINDS","Argentina"
Swiss International Air Lines","Swiss Airlines","LX","SWR","SWISS","Switzerland"
Swissair",\\N,"SR","SWR","Swissair","Switzerland"
Swiss European Air Lines","Swiss European","","SWU","EUROSWISS","Switzerland"
Swe Fly",\\N,"WV","SWV","FLYING SWEDE","Sweden"
SunExpress",\\N,"XQ","SXS","SUNEXPRESS","Turkey"
Syrian Arab Airlines",\\N,"RB","SYR","SYRIANAIR","Syrian Arab Republic"
Skywalk Airlines",\\N,"AL","SYX","SKYWAY-EX","United States"
Shandong Airlines",\\N,"SC","CDG","SHANDONG","China"
SAS Braathens",\\N,"","CNO","SCANOR","Norway"
Spring Airlines",\\N,"9S","CQH","AIR SPRING","China"
Sichuan Airlines",\\N,"3U","CSC","SI CHUAN","China"
Shanghai Airlines",\\N,"FM","CSH","SHANGHAI AIR","China"
Shenzhen Airlines",\\N,"ZH","CSZ","SHENZHEN AIR","China"
Sun D'Or",\\N,"7L","ERO","ECHO ROMEO","Israel"
SkyEurope",\\N,"NE","ESK","RELAX","Slovakia"
Sky Europe Airlines",\\N,"","HSK","MATRA","Slovakia"
Spanair",\\N,"JK","JKK","SPANAIR","Spain"
Spirit Airlines",\\N,"NK","NKS","SPIRIT WINGS","United States"
SATENA",\\N,"9R","NSE","SATENA","Colombia"
Skywest Airlines",\\N,"","OZW","OZWEST","Australia"
Santa Barbara Airlines",\\N,"S3","BBR","SANTA BARBARA","Venezuela"
Sky Airline",\\N,"H2","SKU","AEROSKY","Chile"
SkyWest",\\N,"OO","SKW","SKYWEST","United States"
Skyways Express",\\N,"JZ","SKX","SKY EXPRESS","Sweden"
Skymark Airlines",\\N,"BC","SKY","SKYMARK","Japan"
SilkAir",\\N,"MI","SLK","SILKAIR","Singapore"
Surinam Airways",\\N,"PY","SLM","SURINAM","Suriname"
Sterling Airlines",\\N,"NB","SNB","STERLING","Denmark"
Skynet Asia Airways",\\N,"6J","SNJ","NEWSKY","Japan"
Solomon Airlines",\\N,"IE","SOL","SOLOMON","Solomon Islands"
Southern Airways",\\N,"","SOU","SOUTHERN EXPRESS","United States"
Saratov Aviation Division",\\N,"6W","SOV","SARATOV AIR","Russia"
Sat Airlines",\\N,"HZ","SOZ","SATCO","Kazakhstan"
South Pacific Island Airways",\\N,"","SPI","SOUTH PACIFIC","United States"
Shuttle America",\\N,"S5","TCF","MERCURY","United States"
Scat Air","","DV","VSV","VLASTA","Kazakhstan"
TAME",\\N,"EQ","TAE","TAME","Ecuador"
TAM Brazilian Airlines",\\N,"JJ","TAM","TAM","Brazil"
TAP Portugal","TAP Air Portugal","TP","TAP","AIR PORTUGAL","Portugal"
Tunisair",\\N,"TU","TAR","TUNAIR","Tunisia"
Thai Air Cargo",\\N,"T2","TCG","THAI CARGO","Thailand"
Thomas Cook Airlines",\\N,"FQ","TCW","THOMAS COOK","Belgium"
Thomas Cook Airlines",\\N,"MT","TCX","KESTREL","United Kingdom"
Trigana Air Service",\\N,"","TGN","TRIGANA","Indonesia"
Tiger Airways",\\N,"TR","TGW","GO CAT","Singapore"
Tiger Airways Australia",\\N,"TT","TGW","GO CAT","Australia"
Thai Airways International",\\N,"TG","THA","THAI","Thailand"
Turk Hava Kurumu Hava Taksi Isletmesi",\\N,"","THK","HUR KUS","Turkey"
Thai AirAsia","Thai Air Asia","FD","AIQ","THAI ASIA","Thailand"
Turkish Airlines",\\N,"TK","THY","TURKAIR","Turkey"
Tajikistan International Airlines",\\N,"","TIL","TIL","Tajikistan"
Twin Jet",\\N,"T7","TJT","TWINJET","France"
Translift Airways",\\N,"","TLA","TRANSLIFT","Ireland"
Trans Mediterranean Airlines",\\N,"TL","TMA","TANGO LIMA","Lebanon"
Tiara Air",\\N,"3P","TNM","TIARA","Aruba"
Thomsonfly",\\N,"BY","TOM","TOMSON","United Kingdom"
Tropic Air",\\N,"PM","TOS","TROPISER","Belize"
TAMPA",\\N,"QT","TPA","TAMPA","Colombia"
TransAsia Airways",\\N,"GE","TNA","TransAsia","Taiwan"
Transavia Holland",\\N,"HV","TRA","TRANSAVIA","Netherlands"
TACV",\\N,"VR","TCV","CABOVERDE","Portugal"
Transwest Air",\\N,"9T","ABS","ATHABASKA","Canada"
Transaero Airlines",\\N,"UN","TSO","TRANSOVIET","Russia"
Turkmenistan Airlines","Turkmenhovayollary","T5","TUA","TURKMENISTAN","Turkmenistan"
Tuninter",\\N,"UG","TUI","","Tunisia"
Travel Service",\\N,"QS","TVS","SKYTRAVEL","Czech Republic"
TUIfly Nordic",\\N,"6B","BLX","BLUESCAN","Sweden"
TAAG Angola Airlines",\\N,"DT","DTA","DTA","Angola"
Turkish Air Force",\\N,"","HVK","TURKISH AIRFORCE","Turkey"
TAM Mercosur",\\N,"PZ","LAP","PARAGUAYA","Paraguay"
Trans States Airlines",\\N,"AX","LOF","WATERSKI","United States"
Tarom",\\N,"RO","ROT","TAROM","Romania"
Turan Air",\\N,"3T","URN","TURAN","Azerbaijan"
TRIP Linhas A",\\N,"8R","TIB","TRIP","Brazil"
USA3000 Airlines",\\N,"U5","GWY","GETAWAY","United States"
United Airlines",\\N,"UA","UAL","UNITED","United States"
United Air Charters",\\N,"","UAC","UNITAIR","Zimbabwe"
Ural Airlines",\\N,"U6","SVR","SVERDLOVSK AIR","Russia"
UM Airlines",\\N,"UF","UKM","UKRAINE MEDITERRANEE","Ukraine"
US Airways",\\N,"US","USA","U S AIR","United States"
US Helicopter",\\N,"","USH","US-HELI","United States"
UTair Aviation",\\N,"UT","UTA","UTAIR","Russia"
United States Air Force",\\N,"","AIO","AIR CHIEF","United States"
Uzbekistan Airways",\\N,"HY","UZB","UZBEK","Uzbekistan"
Ukraine International Airlines",\\N,"PS","AUI","UKRAINE INTERNATIONAL","Ukraine"
US Helicopter Corporation",\\N,"UH","","","United States"
Valuair",\\N,"VF","VLU","VALUAIR","Singapore"
Vasco Air",\\N,"","VFC","VASCO AIR","Vietnam"
Vietnam Airlines",\\N,"VN","HVN","VIET NAM AIRLINES","Vietnam"
VIM Airlines",\\N,"NN","MOV","MOV AIR","Russia"
Volaris",\\N,"Y4","VOI","VOLARIS","Mexico"
Volga-Dnepr Airlines",\\N,"VI","VDA","VOLGA-DNEPR","Russia"
Virgin America",\\N,"VX","VRD","REDWOOD","United States"
Virgin Express",\\N,"TV","VEX","VIRGIN EXPRESS","Belgium"
Virgin Nigeria Airways",\\N,"VK","VGN","VIRGIN NIGERIA","Nigeria"
Virgin Atlantic Airways",\\N,"VS","VIR","VIRGIN","United Kingdom"
Viva Macau",\\N,"ZG","VVM","JACKPOT","Macao"
Volare Airlines",\\N,"VE","VLE","VOLA","Italy"
Vueling Airlines",\\N,"VY","VLG","VUELING","Spain"
Vladivostok Air",\\N,"XF","VLK","VLADAIR","Russia"
Varig Log",\\N,"LC","VLO","VELOG","Brazil"
Virgin Australia",\\N,"VA","VOZ","VIRGIN","Australia"
VRG Linhas Aereas","Varig","RG","VRN","VARIG","Brazil"
VASP",\\N,"VP","VSP","VASP","Brazil"
VLM Airlines",\\N,"VG","VLM","RUBENS","Belgium"
Wayraper",\\N,"7W","","WAYRAPER","Peru"
WebJet Linhas A",\\N,"WJ","WEB","WEB-BRASIL","Brazil"
Welcome Air",\\N,"2W","WLC","WELCOMEAIR","Austria"
West Coast Air",\\N,"8O","","","Canada"
WestJet",\\N,"WS","WJA","WESTJET","Canada"
Western Airlines",\\N,"WA","WAL","WESTERN","United States"
Widerøe",\\N,"WF","WIF","WIDEROE","Norway"
Wind Jet",\\N,"IV","JET","GHIBLI","Italy"
Wings Air",\\N,"IW","WON","WINGS ABADI","Indonesia"
Wizz Air",\\N,"W6","WZZ","WIZZ AIR","Hungary"
Wizz Air Hungary",\\N,"8Z","WVL","WIZZBUL","Bulgaria"
World Airways",\\N,"WO","WOA","WORLD","United States"
XL Airways France",\\N,"SE","SEU","STARWAY","France"
Xiamen Airlines",\\N,"MF","CXA","XIAMEN AIR","China"
Yamal Airlines",\\N,"YL","LLM","YAMAL","Russia"
Yemenia",\\N,"IY","IYE","YEMENI","Yemen"
Yuzhmashavia",\\N,"","UMK","YUZMASH","Ukraine"
Zanair",\\N,"","TAN","ZANAIR","Tanzania"
Zoom Airlines",\\N,"Z4","OOM","ZOOM","Canada"
Tyrolean Airways",\\N,\\N,"TYR","TYROLEAN",\\N
Maldivian Air Taxi",\\N,"8Q",\\N,\\N,"Maldives"
Sky Express","SkyExpress","XW","SXR","SKYSTORM","Russia"
Royal Air Cambodge","","VJ","RAC","","Cambodia"
Air Mandalay","","6T",\\N,"Six Tango","Burma"
Air Busan",\\N,"BX","ABL","Air Busan","Republic of Korea"
Globus","","GH","GLP","","Russia"
Air Kazakhstan","","9Y","KZK","Kazakh","Kazakhstan"
Japan Air System","","JD","JAS","Air System","Japan"
EasyJet (DS)","","DS",\\N,"","Switzerland"
Star Peru (2I)","","2I",\\N,"","Peru"
Carnival Air Lines","","KW",\\N,"Carnival Air","United States"
United Airways","","4H","UBD","UNITED BANGLADESH","Bangladesh"
Fly540","","5H","FFV","SWIFT TANGO","Kenya"
Transavia France","","TO","TVF","FRENCH SUN","France"
Island Air (WP)","","WP","MKU","","United States"
Uni Air","","B7","UIA","Glory","Taiwan"
Gomelavia","","YD",\\N,"","Belarus"
Red Wings","Avialinii 400","WZ","RWZ","AIR RED","Russia"
TUIfly (X3)","","11",\\N,"","Germany"
Felix Airways","","FU","FXX","","Yemen"
Kostromskie avialinii","","K1","KOQ","","Russia"
Greenfly","","XX","GFY","","Spain"
Tajik Air","","7J",\\N,"","Tajikistan"
Air Mozambique","","TM",\\N,"","Mozambique"
ELK Airways","","--","ELK","","Estonia"
Gabon Airlines",\\N,"GY","GBK","GABON AIRLINES","Gabon"
MCA Airlines","","","MCA","CALSON","Sweden"
Maldivo Airlines","","ML","MAV","Maldivo","Maldives"
Virgin Pacific","","VH","VNP","","Fiji"
Zest Air","","Z2",\\N,"","Philippines"
Yangon Airways","","HK",\\N,"Hotel Kilo","Burma"
Eastar Jet","","ZE","ESR","Eastar","South Korea"
Jin Air","","LJ","JNA","Jin Air","South Korea"
Wataniya Airways","","","KW1","","Kuwait"
Air Arabia Maroc","","3O",\\N,"Air Arabia","Morocco"
Baltic Air lines","","B1","BA1","Baltic","Latvia"
Ciel Canadien","","YC","YCC","Ciel","Canada"
Canadian National Airways","","CN","YCP","CaNational","Canada"
Epic Holiday","Epic Holidays","FA","4AA","Epic","United States"
Indochina Airlines","","","AXC","Airspup","Vietnam"
Air Comet Chile","","3I",\\N,"","Chile"
German Air Force - FLB","","","FLB","FLB","Germany"
Line Blue","","L8","LBL","Bluebird","Germany"
FlyLAL Charters","","","LLC","","Lithuania"
Salzburg arrows","SZA","SZ",\\N,"SZA","Austria"
Texas Wings","","TQ","TXW","TXW","United States"
Dennis Sky","Dennis Sky Holding","DH","DSY","DSY","Israel"
Zz","","ZZ",\\N,"","Belgium"
Atifly","","A1","A1F","atifly","United States"
Aerolineas heredas santa maria","","","SZB","","Dominican Republic"
Ciao Air","","99",\\N,"","Italy"
Jc royal.britannica","","","JRB","","United Kingdom"
Pal airlines","","5P",\\N,"","Chile"
CanXpress","","C1","CA1","CAX","Canada"
Danube Wings (V5)","","V5",\\N,"","Slovakia"
Sharp Airlines","","SH","SHA","SHARP","Australia"
CanXplorer","","C2","CAP","","Canada"
Click (Mexicana)","","QA",\\N,"","Mexico"
World Experience Airline","WEA","W1","WE1","WEA","Canada"
ALAK","","J4",\\N,"","Russia"
Air Choice One","","3E",\\N,"","United States"
Tianjin Airlines","","","GCR","","China"
China United","","KN",\\N,"","China"
Locair","","ZQ","LOC","LOCAIR","United States"
Safi Airlines","","4Q",\\N,"","Afghanistan"
SeaPort Airlines","","K5","SQH","SASQUATCH","United States"
Salmon Air","","S6",\\N,"","United States"
Bobb Air Freight","","01",\\N,"","Germany"
Star1 Airlines","","V9","HCW","","Lithuania"
Pelita","","6D",\\N,"","Indonesia"
Alaska Seaplane Service","","J5",\\N,"","United States"
Enerjet","","","ENJ","ENERJET AIR","Canada"
MexicanaLink","","I6","MXI","LINK","Mexico"
Island Spirit","","IP","ISX","","Iceland"
TACA Peru","","T0",\\N,"TACA PERU","Peru"
Orbest","","","OBS","ORBEST","Portugal"
Southern Air Charter","","","SOA","","Bahamas"
SVG Air","","","SVG","Grenadines","Saint Vincent and the Grenadines"
Air Century","","","CEY","","Dominican Republic"
Pan Am World Airways Dominicana","PAWA Dominicana","7Q",\\N,"PAWA","Dominican Republic"
Primera Air","","PF",\\N,"PRIMERA","Iceland"
Air Antilles Express","","3S",\\N,"GREEN BIRD","Guadeloupe"
Sol Lineas Aereas","","","OLS","FLIGHT SOL","Argentina"
Regional Paraguaya","","P7","REP","REGIOPAR","Paraguay"
VIP Ecuador","","V6",\\N,"","Ecuador"
Transportes Aereos Cielos Andinos","","","NDN","ANDINOS","Peru"
Peruvian Airlines","","P9",\\N,"","Peru"
EasyFly","","","EFY","EASYFLY","Colombia"
Polar Airlines","","ЯП",\\N,"","Russia"
Catovair","","OC",\\N,"CATOVAIR","Mauritius"
Andalus Lineas Aereas","","","ANU","Andalus","Spain"
Air 26","","","DCD","DUCARD","Angola"
Mauritania Airways","","","MTW","MAURITANIA AIRWAYS","Mauritania"
CEIBA Intercontinental","","","CEL","CEIBA LINE","Equatorial Guinea"
Halcyonair","","7Z",\\N,"CREOLE","Cape Verde"
Business Aviation","","4P",\\N,"AFRICAN BUSINESS","Congo (Kinshasa)"
Compagnie Africaine d\\'Aviation","","E9",\\N,"AFRICOMPANY","Congo (Kinshasa)"
Zambia Skyways","","K8",\\N,"ZAMBIA SKIES","Zambia"
AlMasria Universal Airlines","","UJ","LMU","ALMASRIA","Egypt"
EgyptAir Express","","","MSE","EGYPTAIR EXPRESS","Egypt"
SmartLynx Airlines","","6Y",\\N,"","Latvia"
Air Italy Egypt","","","EUD","","Egypt"
KoralBlue Airlines","","K7","KBR","KORAL BLUE","Egypt"
Wind Rose Aviation","","","WRC","WIND ROSE","Ukraine"
Elysian Airlines","","E4","GIE","","Cameroon"
Sevenair","","","SEN","SEVENAIR","Tunisia"
Hellenic Imperial Airways","","HT","IMP","IMPERIAL","Greece"
Amsterdam Airlines","","WD","AAN","AMSTEL","Netherlands"
Arik Niger","","Q9","NAK","","Niger"
Dana Air","","DA",\\N,"DANACO","Nigeria"
STP Airways","","8F","STP","SAOTOME AIRWAYS","Sao Tome and Principe"
Med Airways","","7Y",\\N,"FLYING CARPET","Lebanon"
Skyjet Airlines","","UQ","SJU","SKYJET","Uganda"
Air Volga","","G6",\\N,"GOUMRAK","Russia"
Transavia Denmark","","","TDK","","Denmark"
Royal Falcon","","RL","RFJ","","Jordan"
Euroline","","4L","MJX","GEO-LINE","Georgia"
Turkuaz Airlines","","","TRK","TURKU","Turkey"
Athens Airways","","ZF",\\N,"ATHENSAIR","Greece"
Viking Hellas","","VQ","VKH","DELPHI","Greece"
Norlandair","","","FNA","NORLAND","Iceland"
Flugfelag Vestmannaeyja","","","FVM","ELEGANT","Iceland"
Starline.kz","","DZ",\\N,"ALUNK","Kazakhstan"
Lugansk Airlines","","L7",\\N,"ENTERPRISE LUHANSK","Ukraine"
Gryphon Airlines","","6P",\\N,"","United States"
Gadair European Airlines","","GP","GDR","GADAIR","Spain"
Spirit of Manila Airlines","","SM","MNP","MANILA SKY","Philippines"
Chongqing Airlines","","OQ","CQN","CHONG QING","China"
Grand China Air","","","GDC","GRAND CHINA","China"
West Air China","","PN","CHB","WEST CHINA","China"
QatXpress","qatXpress","C3","QAX","","Qatar"
OneChina","OneChina","1C","1CH","","China"
NordStar Airlines","","Y7",\\N,"","Russia"
Joy Air","","JR","JOY","JOY AIR","China"
Air India Regional","","CD",\\N,"ALLIED","India"
MDLR Airlines","","9H",\\N,"MDLR","India"
Jagson Airlines","","","JGN","JAGSON","India"
Maldivian","","Q2",\\N,"ISLAND AVIATION","Maldives"
Xpressair","","XN",\\N,"","Indonesia"
Strategic Airlines","","VC",\\N,"","Australia"
Fars Air Qeshm","","","QFZ","FARS AIR","Iran"
Eastok Avia","","","EAA","","Kyrgyzstan"
Jupiter Airlines","","","JPU","JUPITERAIR","United Arab Emirates"
Vision Air International","","","VIS","","Pakistan"
Al-Naser Airlines","","NA",\\N,"","Iraq"
Fuji Dream Airlines","","JH",\\N,"FUJI DREAM","Japan"
Korea Express Air","","","KEA","","South Korea"
Eznis Airways","","","EZA","EZNIS","Mongolia"
Pacific Flier","","","PFL","KOROR","Palau"
Syrian Pearl Airlines","","","PSB","","Syria"
SGA Airlines","","5E",\\N,"SIAM","Thailand"
Air2there","","F8",\\N,"","New Zealand"
Avianova (Russia)","","AO",\\N,"Nova","Russia"
Parmiss Airlines (IPV)","","PA","IPV","IPV","Iran"
EuropeSky","","ES","EUV","EuropeSky","Germany"
BRAZIL AIR","BRAZIL AIR","GB","BZE","BRAZIL AIR","Brazil"
Homer Air","Homer Sky","MR","OME","","Germany"
U.S. Air","","-+","--+","","United States"
Jayrow","","\\'","\\'\\","","Australia"
Wilderness Air","",";;",\\N,"","Australia"
Whitaker Air","","^^",\\N,"","Australia"
PanAm World Airways","","WQ","PQW","","United States"
Virginwings","","YY","VWA","","Germany"
KSY","Kreta Sky","KY","KSY","KSY","Greece"
Buquebus Líneas Aéreas","","BQ","BQB","","Uruguay"
SOCHI AIR","SOCHI","CQ","KOL","SLOW FROG","Russia"
Wizz Air Ukraine","","WU","WAU","WIZZAIR UKRAINE","Ukraine"
88","","47","VVN","","Cyprus"
LCM AIRLINES","","LQ","LMM","","Russia"
Cambodia Angkor Air (K6)","","K6",\\N,"","Cambodia"
Royal European Airlines","","69",\\N,"","United Kingdom"
Tom\\'s & co airliners","Tom\\'s air","&T","T&O","T&","France"
Azul","Azul Linhas Aéreas Brasileiras","AD","AZU","","Brazil"
LSM Airlines","slowbird","PQ","LOO","slowbird","Russia"
Zapolyarie Airlines","Zapolyarye Airlines","","PZY","","Russia"
Finlandian","","","FN1","","Finland"
LionXpress","lionXpress","C4","LIX","LIX","Cameroon"
Genesis","","GK",\\N,"","Pakistan"
Congo Express","","XZ",\\N,"EXPRESSWAYS","Congo (Kinshasa)"
Fly Dubai","","FZ","FDB","","United Arab Emirates"
Domenican Airlines","Domenican","D1","MDO","Domenican","Dominican Republic"
ConneX European Airline","","","2CO","ConneX","Austria"
Aereonautica militare","","JY","AXZ","","Italy"
Kal Star Aviation","","","KLS","","Indonesia"
LSM AIRLINES ","Russian. Yours Air Lines ","YZ","YZZ","Moscow frog ","Russia"
UTair-Express","","UR",\\N,"","Russia"
Huaxia","HUAXIA","G5",\\N,"","China"
Zabaykalskii Airlines","Baikal Airlines","ZP","ZZZ","Lakeair","Russia"
CBM America","","","XBM","AIRMAX","United States"
Marysya Airlines","MARYSYA AIRLINES","M4","1QA","MARSHAK AIR","Russia"
N1","","N1",\\N,"","Peru"
Airlink (SAA)","","4Z",\\N,"","South Africa"
Westfalia Express VA","","","WFX","","Germany"
JobAir","","3B",\\N,"","Czech Republic"
Black Stallion Airways","","BZ","BSA","Stallion","United States"
German International Air Lines","Germanair","GM","GER","","Germany"
TrasBrasil","","TB","TBZ","","Brazil"
TransBrasil Airlines","","TH","THS","","Brazil"
China SSS","Chunqiu Airlines","9C",\\N,"","China"
AIR INDOCHINE","","","IIA","","Vietnam"
Happy Air","","","HPY","","Thailand"
Solar Air","","","SRB","Solar Air","Thailand"
Air Mekong","","P8","MKG","Air Mekong","Vietnam"
Harbour Air (Priv)","","H3",\\N,"","Canada"
Air Hamburg (AHO)","","HH","AHO","Air Hamburg","Germany"
ZABAIKAL AIRLINES","ZABAIKAL ","Z6","ZTT","BAIKAL ","Russia"
TransHolding","Trans","TI","THI","","Brazil"
SUR Lineas Aereas","","","SZZ","","Argentina"
Aerolineas Africanas","","","AA1","","Guinea"
Yeti Airways","","YT",\\N,"","Nepal"
Yellowstone Club Private Shuttle","","Y1",\\N,"YCS","United States"
Caucasus Airlines","","NS",\\N,"","Georgia"
Serbian Airlines","","S1","SA1","","Serbia"
Windward Islands Airways","","WM",\\N,"Winair","Netherlands Antilles"
TransHolding System","","YO","TYS","","Brazil"
CCML Airlines","","CB","CCC","","Colombia"
Small Planet Airlines","","","ELC","","Lithuania"
Fly Brasil","Fly Brasil","F1","FBL","FBL","Brazil"
CB Airways UK ( Interliging Flights )","","1F","CIF","","United Kingdom"
Fly Colombia ( Interliging Flights )","","3F","3FF","","Colombia"
Trans Pas Air","","T6","TP6","","United States"
KMV","","МИ",\\N,"Air Minvody","Russia"
Himalayan Airlines","Himalaya","HC","HYM","Himalayan","Nepal"
Indya Airline Group","Indya1","G1","IG1","Indya1","India"
Sunwing","","WG",\\N,"sunwing","Canada"
Turkish Wings Domestic","","","TWD","TWD","Turkey"
Japan Regio","","ZX","ZXY","","Japan"
OCEAN AIR CARGO","","","IXO","","India"
Norte Lineas Aereas","NORTE","N0",\\N,"","Argentina"
Austral Brasil","Austral Brasil lineas aereas","W7",\\N,"","Brazil"
PEGASUS AIRLINES-","","H9",\\N,"","Turkey"
Nihon.jet connect","","","NX1","","Kyrgyzstan"
Camair-co","","QC",\\N,"","Cameroon"
Sky Regional","Air Canada Express","RS","SKV","Sky Regional","Canada"
LSM International ","Moskva-air","II","UWW","moose","Russia"
Baikotovitchestrian Airlines ","","BU","BUU","","American Samoa"
Luchsh Airlines ","Air luch","L4","LJJ","russian sky","Russia"
ENTERair","","","QQQ","","Poland"
Air Cargo Germany","","6U",\\N,"Loadmaster","Germany"
Mongolian International Air Lines ","Mongol Air ","7M","ZTF","Mongol_AIr ","Mongolia"
Tway Airlines","","TW","TWB","TWAY AIR","South Korea"
Papillon Grand Canyon Helicopters","","HI",\\N,"","United States"
Jusur airways","","JX","JSR","","Egypt"
NEXT Brasil","NEXT","XB","NXB","XB","Brazil"
AeroWorld ","Sovet Air ","W4","WER","sovet","Russia"
GNB Linhas Aereas","","GN",\\N,"","Brazil"
Usa Sky Cargo","USky","E1","ES2","USKY","United States"
Hankook Airline","","HN","HNX","HNX","South Korea"
REDjet","","Z7",\\N,"","Barbados"
Red Jet Andes","","PT",\\N,"","Peru"
Red Jet Canada","","QY",\\N,"","Canada"
Sprintair","","","SRN","","Poland"
Red Jet Mexico","","4X",\\N,"","Mexico"
Marusya Airways","Marusya Air","Y8","MRS","snowball","Russia"
Era Alaska","","7H","ERR","ERAH","United States"
AirRussia","RussianConector","R8","RRJ","russiancloud","Russia"
Hankook Air US","","H1","HA1","","United States"
Carpatair Flight Training","","","SMW","Smartwings","Romania"
I-Fly","","H5","RSY","RUSSIAN SKY","Russia"
Whitejets","","","WTJ","WHITEJET","Brazil"
VickJet","","KT","VKJ","Vickjet","France"
BVI Airways","","XV",\\N,"","British Virgin Islands"
Hamburg Airways","","","HAY","","Germany"
Salsa d\\'Haiti","","SO","SLC","SALSA","Haiti"
Zambezi Airlines (ZMA)","","ZJ",\\N,"","Zambia"
Kan Air","","","KND","Kan Air","Thailand"
Air Cudlua","Air Cudlua","","CUD","Cudlua","United Kingdom"
Polet Airlines (Priv)","","YQ",\\N,"","Russia"
Air Explore","","","AXE","","Slovakia"
12 North","","12","N12","12N","India"
Holidays Czech Airlines","","","HCC","","Czech Republic"
Comtel Air","","","COE","","Austria"
Mint Airways","","","MIC","","Spain"
Orbit Airlines","Orbit","","OBT","Orbit","United States"
Air Bucharest","","","BUR","","Romania"
AlbaStar","","","LAV","","Spain"
Mauritania Airlines International","","L6","MAI","","Mauritania"
MAT Airways","","6F","MKD","","Macedonia"
Asian Wings Airways","","AW","AWM","Asian Star","Burma"
Air Arabia Egypt","","E5","RBG","","Egypt"
Eagles Airlines","","","EGS","EAGLES","Italy"
YES Airways","","","YEP","","Poland"
Alitalia Cityliner","","CT",\\N,"","Italy"
Direct Aero Services","","","DSV","","Romania"
Medallion Air","","","MDP","MEDALS","Romania"
Orchid Airlines","","OI","ORC","","Australia"
Asia Wings","","Y5","AWA","","Kazakhstan"
Georgian International Airlines","","","GNN","GEO-LINE","Georgia"
Air Batumi","","","BTM","","Georgia"
Skywest Australia","","XR",\\N,"","Australia"
Nile Air","","NP","NIA","NILEBIRD","Egypt"
Feeder Airlines","","","FDD","","Sudan"
Senegal Airlines","","DN","SGG","","Senegal"
Fly 6ix","","6I",\\N,"","Sierra Leone"
Starbow Airlines","","S9",\\N,"","Ghana"
Copenhagen Express","","0X","CX0","Copex","Denmark"
BusinessAir","","8B","BCC","","Thailand"
SENIC AIRLINES","","YR",\\N,"","United States"
XOJET","","","XOJ","","United States"
Sky Wing Pacific","","C7","CR7","","South Korea"
Bateleur Air","","","BEU","","South Africa"
Air Indus","Indus Airlines Pak","PP","AI0","AIPL","Pakistan"
Orbit International Airlines","","","OAI","OA","United States"
Orbit Regional Airlines","","","OAR","OA","United States"
Orbit Atlantic Airways","","","OAN","","United States"
Volotea","","","VOO","Volotea","Spain"
Peach Aviation","","MM",\\N,"Air Peach","Japan"
Helitt Líneas Aéreas","","","HTH","","Spain"
Russia State Transport","Federal State Budget Inst","","RSD","STATE AERO","Russia"
Malaysia Wings","","","MWI","MWI","Malaysia"
Aviabus","","U1","ABI","","Russia"
Michael Airlines","Javi","DF","MJG","MJG","Puerto Rico"
Korongo Airlines","","ZC","KGO","KORONGO","Congo (Kinshasa)"
Indonesia Sky","","I5","IDS","","Indonesia"
Aws express","","B0","666","aws","United States"
Southjet","","76","SJS","","United States"
Southjet connect","","77","ZCS","","United States"
Southjet cargo","","78","XAN","","United States"
Iberia Express","","I2","IBS","","Spain"
Interjet (ABC Aerolineas)","","4O",\\N,"INTERJET","Mexico"
AirOnix","","OG",\\N,"","Ukraine"
Nordic Global Airlines","","NJ","NGB","Nordic Global","Finland"
Scoot","","TZ","SCO","","Singapore"
Hi Fly (5K)","","5K",\\N,"","Portugal"
China Northwest Airlines (WH)","","WH",\\N,"","China"
Zenith International Airline","Zenith","ZN","ZNA","ZENITH","Thailand"
Orbit Airlines Azerbaijan","Orbit Azerbaijan","O1","OAB","Orbitaz","Azerbaijan"
Air Alps Aviation (A6)","","A6",\\N,"ALPAV","Austria"
Flying kangaroo Airline","Skippy","","FKA","Skippy","Australia"
RusJet","","","RSJ","","Russia"
VietJet Air","VietJet","","VJC","VIETJETAIR","Vietnam"
Patriot Airways","","P4",\\N,"","United States"
Vision Airlines (V2)","","V2","RBY","RUBY","United States"
BQB Lineas Aereas","Buquebus","5Q",\\N,"","Uruguay"
AirAsia Japan","","","WAJ","WING ASIA","Japan"
Yellowtail","","YE","YEL","","United States"
Royal Airways","Royal Inc.","KG","RAW","RAW","United States"
FlyHigh Airlines Ireland (FH)","","FH","FHI","FLYHIRELAND","Ireland"
Executive AirShare","","","XSR","","United States"
Hebei Airlines","","","HBH","Hebei Air","China"
Air KBZ","","","KBZ","Air KBZ","Burma"
Aero VIP (2D)","","2D",\\N,"","Portugal"
Yangon Airways Ltd.","","YH",\\N,"","Burma"
T.J. Air","","TJ","TJA","T.J. Air","United States"
SkyWork Airlines ","","SX",\\N,"SKYFOX","Switzerland"
Maastricht Airlines","","W2",\\N,"","Netherlands"
Euro Jet","","24",\\N,"","Germany"
Ukraine Atlantic","","","UAT","","Ukraine"
Nesma Airlines","","","NMA","Nesma Airlines","Egypt"
East Horizon","","","EHN","EAST HORIZON","Afghanistan"
Air Majoro","","","MJP","Air Majoro","Peru"
Rotana Jet","","","RJD","ROTANA","United Arab Emirates"
SOCHI AIR CHATER","Sochi Air ","Q3","QER","russian doll","Russia"
Denim Air ","FlyNonstop","J7",\\N,"DNM","Norway"
Malindo Air","","OD","MXD","Malindo","Malaysia"
Hermes Airlines","","","HRM","HERMES","Greece"
Flightlink Tanzania","Flightlink","Z9",\\N,"","Tanzania"
IzAvia","","I8",\\N,"","Russia"
Катэкавиа","","","КТК","","Russia"
Псковавиа","Псков Авиа","","PKV","","Russia"
Maryland Air","Maryland","M1","M1F","Maryland Flight","United States"
Insel Air (7I/INC) (Priv)","","7I",\\N,"","Netherlands Antilles"
VivaColombia","","5Z","VVC","","Colombia"
Flybe Finland Oy","","","FCM","FINNCOMM","Finland"
Bingo Airways","Bingo","","BGY","","Poland"
Bluebird Airways (BZ)","","","BBG","","Greece"
Apache Air","Apache","ZM","IWA","APACHE","United States"
MHS Aviation GmbH","","M2",\\N,"","Germany"
Jettor Airlines","Jettor","NR","JTO","JETHAPPY","Hong Kong"
Flyme (VP)","","","VQI","","Maldives"
Thai Lion Air","","SL",\\N,"","Thailand"
Golden Myanmar Airlines","","","GMR","Golden Myanmar","Burma"
Canaryfly","","","CNF","","Spain"
Sunrise Airways","","","KSZ","","Haiti"
National Air Cargo","","N8","NCR","","United States"
Eastern Atlantic Virtual Airlines","","13","EAV","EAVA","United States"
Citilink Indonesia","","QG",\\N,"SUPERGREEN","Indonesia"
Transair","","","TTZ","","Canada"
Comfort Express Virtual Charters Albany","","","EVC","Comfort Express","United States"
Comfort Express Virtual Charters","","","CEO","","United States"
FLYJET","","","FYJ","Fast Jet","Poland"
Snowbird Airlines","","S8","SBD","","Finland"
Russkie Krylya","","","KRY","","Russia"
Kharkiv Airlines","","KH","KHK","","Ukraine"
XAIR USA","","XA","XAU","XAIR","United States"
Air Costa","","LB",\\N,"","India"
Simrik Airlines","","","RMK","","Nepal"
XPTO","XPTO  ","XP","XPT","XPTO","Portugal"
Royal Flight","","","DME","","Russia"
BBN-Airways","BlackBurn","","EGH","BBN","United Kingdom"
Tomsk-Avia","","","TKS","","Russia"
Malawian Airlines","","3W",\\N,"","Malawi"
Yeti Airlines ","","","NYT","","Nepal"
Avilu","Avilu' SA","..","...","","Switzerland"
Air Serbia",\\N,"JU","ASL","AIR SERBIA","Serbia"
Skyline Ulasim Ticaret A.S.","Skyline Ulasim Ticaret A.S.","","KCU","Kocoglu","Turkey"
Air Lituanica","Air Lituanica","LT","LTU","LITUANICA","Lithuania"
Envoy Air","","","ENY","Envoy","United States"
CARICOM AIRWAYS (BARBADOS) INC.","CARICOM AIRWAYS","","CCB","","Barbados"
Rainbow Air (RAI)","Rainbow Air (RAI)","RN","RAB","Rainbow","United States"
Rainbow Air Canada","Rainbow Air CAN","RY","RAY","Rainbow CAN","Canada"
Rainbow Air Polynesia","Rainbow Air POL","RX","RPO","Rainbow Air","United States"
Rainbow Air Euro","Rainbow Air EU","RU","RUE","Rainbow Air","United Kingdom"
Rainbow Air US","Rainbow Air US","RM","RNY","Rainbow Air","United States"
Transilvania","","","TNS","","Romania"
Dobrolet","Добролёт","QD","DOB","DOBROLET","Russia"
Spike Airlines","Aero Spike","S0","SAL","Spike Air","United States"
Grand Cru Airlines","","","GCA","","Lithuania"
Go2Sky","","","RLX","RELAX","Slovakia"
All Argentina","All Argentina","L1","AL1","","Argentina"
All America","All America","A2","AL2","","United States"
All Asia","All Asia","L9","AL3","","China"
All Africa","All Africa","9A","99F","","South Africa"
Regionalia México","Regionalia México","N4","J88","","Mexico"
All Europe","All Europe","N9","N99","","United Kingdom"
All Spain","All Spain","N7","N77","","Spain"
Regional Air Iceland","Regional Air Iceland","9N","N78","","Iceland"
Voestar","Voestar Brasil","8K","K88","","Brazil"
All Colombia","All Colombia","7O","7KK","","Colombia"
Regionalia Uruguay","Regionalia Uruguay","2X","2K2","","Uruguay"
Regionalia Venezuela","Regionalia Venezuela","9X","9XX","","Venezuela"
Regionalia Chile","Regionalia Chile","9J","CR1","","Chile"
Vuela Cuba","Vuela Cuba","6C","6CC","","Cuba"
All Australia","All Australia","88","8K8","","Australia"
Fly Europa","","ER","RWW","","Spain"
FlyPortugal","","PO","FPT","FlyPortugal","Portugal"
Spring Airlines Japan","","IJ","SJO","","Japan"
Dense Airways","","KP","DWA","DENSE","United States"
Dense Connection","","KZ","DC2","DC2","United States"
Vuola Italia","Vuola Italia","4S","VI4","","Italy"
Jet Suite","","","RSP","Red Stripe","United States"
Fly Jamaica Airways","","","FJM","Greenheart","Jamaica"
Island Express Air","","1X",\\N,"Abby Air","Canada"
All Argentina Express","All Argentina Express","Z0","Z9H","","Argentina"
Thai Smile Airways","THAI Smile","WE",\\N,"THAI SMILE","Thailand"
International AirLink","","I4",\\N,"","Jamaica"
Real Tonga","","RT",\\N,"","Tonga"
All America AR","All America Argentina","2R","M7A","","Argentina"
All America CL","All America Chile","1R","R1R","","Chile"
SOCHI AIR EXPRESS","ADLER EXPRESS","Q4","SAE","ADLER EXPRESS","Russia"
All America BR","All America Brasil","1Y","A9B","","Brazil"
Volotea Costa Rica","Volotea Costa Rica","9V","VC9","","Costa Rica"
Fly Romania","","X5","OTJ","TENDER AIR","Romania"
Eagle Atlantic Airlines","","E2",\\N,"","Ghana"
Fly Africa Zimbabwe","Zimbabwe flyafrica.com","","FZW","Fresh Express","Zimbabwe"
San Dima Air","(Cyber Airlines) Not Real","","SDI","FAREFLIGHT","United States"
All America CO","All America Colombia","0Y","7ZC","","Colombia"
All America MX","All America México","0M","0MM","","Mexico"
FOX Linhas Aereas","","FX","FOX","","Brazil"
Air Kenya (Priv)","","QP",\\N,"","Kenya"
Via Conectia Airlines","Via Conectia","6V","CZV","","Uruguay"
Hebradran Air Services","","","HBR","Hebradran","United Kingdom"
Pobeda","","","PBD","POBEDA","Russia"
City Airways","","E8","GTA","CITY AIR","Thailand"
Norwegian Long Haul AS","","DU","NLH","NORSTAR","Norway"
BA101","","","710","","United Kingdom"
TransNusa Air","","M8","TNU","TRANSNUSA","Indonesia"
Tomp Airlines","Tomp Airlines","ZT","T9P","","Chile"
Fuzhou Airlines","","","FZA","","China"
Sky Angkor Airlines (ZA)","","","SWM","SKY ANGKOR","Cambodia"
OneJet","","J1",\\N,"","United States"
Global Airlines","Global Airlines","0G","GA0","","Argentina"
Mann Yadanarpon Airlines","","","MYP","MANN ROYAL","Burma"
Air Vistara","Tata SIA Airlines","UK","VTI","","India"
TransRussiaAirlines","TransRus","1E","RGG","","Russia"
Severstal Air Company","","D2",\\N,"","Russia"
REXAIR VIRTUEL","","RR","RXR","Rexair","France"
WestJet Encore","Encore","WR","WEN","Encore","Canada"
Air Pegasus","","OP","PPL","","India"
International Europe","International","9I","INE","","Spain"
Sky Regional Airlines","","","SKV","Maple","Canada"
V Air","V Air Taiwan","ZV","VAX","","Taiwan"
Cello Aviation","","","CLJ","CELLOJET","United Kingdom"
Pouya Air","","","PYA","","Iran"
Boutique Air (Priv)","","4B","BTQ","","United States"
FlyEgypt","FlyEgypt","","FEG","","Egypt"
VOLOTEA Airways","","V7","VOE","","Spain"
INAVIA Internacional","Internacional","Z5","IIR","","Argentina"
Liberty Airways","","LE","LTY","","United States"
Аэросервис","","АЯ",\\N,"","Russia"
Aeronautica Militare","","","IAM","Italian Airforce","Italy"
Bassaka airlines","","5B","BSX","5B","Cambodia"
Jetstar Japan ","","","JJP","ORANGE LINER","Japan"
SkyBahamas Airlines","","Q7",\\N,"TROPICAL SKY","Bahamas"
UVT Aero","","UW",\\N,"","Russia"
First Flying","","","DAK","","Japan"
Silver Airways (3M)","","3M",\\N,"Silver Wings","United States"
AtlasGlobal Ukraine","","","UJX","Atlas Ukraine","Ukraine"
Boliviana de Aviacion (OB)","BoA","","BOV","BOLIVIANA","Bolivia"
US-Bangla Airlines","","","UBG","","Bangladesh"
Norwegian Air International (D8)","","","IBK","NORTRANS","Norway"
ATA Airlines (Iran)","هواپیمایی آتا","I3",\\N,"ATALAR","Iran"
VIA Líneas Aéreas","VIA","V1","VIA","","Argentina"
GermanXL","","GX","GXG","","Germany"
Alghanim","","","KYA","","United States"
Indonesa Air Aisa X","","","IDX","Red Phoenix","Indonesia"
Fly France","Fly France","FF","FRF","","France"
Jota Aviation","","","ENZ","ENZO","United Kingdom"
Europe Jet","Europe Jet","EX","EU9","","France"
COBALT","COBALT","","FCB","COBALT","Cyprus"
Southern Airways Express","Sun Air Express","","LTD","LIGHTSPEED","United States"
Orenburzhie","","","ORG","","Russia"
World Scale Airlines","World Scale","W3","WSS","","United States"
All America US","All America US","AG","SSA","","United States"
University of Birmingham Air Squadron (RAF)","8AEF RAF","","UAY","UAY","United Kingdom"
Choice Airways","","","CSX","","United States"
Aruba Airlines","","","ARU","","Aruba"
BudgetAir","BudgetAir","1K","BG1","","Germany"
Dynamic Airways","","","DYA","","United States"
Fly One","Fly One","F5","FI5","","Moldova"
Nordica","","EE",\\N,"REVAL","Estonia"
Tez Jet Airlines","","","TEZ","","Kyrgyzstan"
Kush Air","","","KUH","","South Sudan"
ViaAir","Charter Air Transport","","SRY","Stingray","United States"
All America BOPY","All America BOPY","0P","PYB","BOPY","Paraguay"
Thai Vietjet Air","","","TVJ","THAIVIET JET","Thailand"
GX Airlines","","","CBG","SPRAY","China"
"""




chunks = str.split(',')


x = chunks[1::5]
print(x)
del chunks[1::5]
print(chunks)
del chunks[1::5]
print(chunks)
del chunks[2::5]
print(chunks)


