import sqlite3

conn = sqlite3.connect('Airport.db')

c = conn.cursor()





c.execute("INSERT INTO Airlines VALUES ('1Time Airline','RNX','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('40-Mile Air','MLA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Ansett Australia','AAA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Aigle Azur','AAF','France')")
c.execute("INSERT INTO Airlines VALUES ('Aloha Airlines','AAH','United States')")
c.execute("INSERT INTO Airlines VALUES ('American Airlines','AAL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Asiana Airlines','AAR','Republic of Korea')")
c.execute("INSERT INTO Airlines VALUES ('Askari Aviation','AAS','Pakistan')")
c.execute("INSERT INTO Airlines VALUES ('Afriqiyah Airways','AAW','Libya')")
c.execute("INSERT INTO Airlines VALUES ('Allegiant Air','AAY','United States')")
c.execute("INSERT INTO Airlines VALUES ('ABSA - Aerolinhas Brasileiras','TUS','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Astral Aviation','ACP','Kenya')")
c.execute("INSERT INTO Airlines VALUES ('Ada Air','ADE','Albania')")
c.execute("INSERT INTO Airlines VALUES ('Adria Airways','ADR','Slovenia')")
c.execute("INSERT INTO Airlines VALUES ('Air Europa','AEA','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Aero Benin','AEB','Benin')")
c.execute("INSERT INTO Airlines VALUES ('Aegean Airlines','AEE','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Air Europe','AEL','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Alaska Central Express','AER','United States')")
c.execute("INSERT INTO Airlines VALUES ('ACES Colombia','AES','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Astraeus','AEU','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Aerosvit Airlines','AEW','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Air Italy','AEY','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Alliance Airlines','UTY','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Ariana Afghan Airlines','AFG','Afghanistan')")
c.execute("INSERT INTO Airlines VALUES ('Aeroflot Russian Airlines','AFL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Air Bosna','BON','Bosnia and Herzegovina')")
c.execute("INSERT INTO Airlines VALUES ('Air France','AFR','France')")
c.execute("INSERT INTO Airlines VALUES ('Air Caledonie International','ACI','France')")
c.execute("INSERT INTO Airlines VALUES ('Air Cargo Carriers','SNC','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Namibia','NMB','Namibia')")
c.execute("INSERT INTO Airlines VALUES ('Aerolitoral','SLI','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('Air Glaciers','AGV','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Aviogenex','AGX','Serbia')")
c.execute("INSERT INTO Airlines VALUES ('Aeroper','PLI','Peru')")
c.execute("INSERT INTO Airlines VALUES ('Atlas Blue','BMM','Morocco')")
c.execute("INSERT INTO Airlines VALUES ('Azerbaijan Airlines','AHY','Azerbaijan')")
c.execute("INSERT INTO Airlines VALUES ('Avies','AIA','Estonia')")
c.execute("INSERT INTO Airlines VALUES ('Airblue','ABQ','Pakistan')")
c.execute("INSERT INTO Airlines VALUES ('Airlift International','AIR','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Berlin','BER','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Air India Limited','AIC','India')")
c.execute("INSERT INTO Airlines VALUES ('Air Bourbon','BUB','Reunion')")
c.execute("INSERT INTO Airlines VALUES ('Air Atlanta Icelandic','ABD','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Air Tahiti Nui','THT','France')")
c.execute("INSERT INTO Airlines VALUES ('Arkia Israel Airlines','AIZ','Israel')")
c.execute("INSERT INTO Airlines VALUES ('Air Jamaica','AJM','Jamaica')")
c.execute("INSERT INTO Airlines VALUES ('Air One','ADH','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Air Sahara','RSH','India')")
c.execute("INSERT INTO Airlines VALUES ('Air Malta','AMC','Malta')")
c.execute("INSERT INTO Airlines VALUES ('Air Japan','AJX','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Air Korea Co. Ltd.','AKA','Republic of Korea')")
c.execute("INSERT INTO Airlines VALUES ('Air Kiribati','AKL','Kiribati')")
c.execute("INSERT INTO Airlines VALUES ('America West Airlines','AWE','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Wisconsin','AWI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Tatarstan Airlines','TAK','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Allegheny Commuter Airlines','ALO','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Sunshine','RSI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Malawi','AML','Malawi')")
c.execute("INSERT INTO Airlines VALUES ('ATA Airlines','AMT','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Macau','AMU','Macao')")
c.execute("INSERT INTO Airlines VALUES ('AMC Airlines','AMV','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Air Seychelles','SEY','Seychelles')")
c.execute("INSERT INTO Airlines VALUES ('AeroMéxico','AMX','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('All Nippon Airways','ANA','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Air Nostrum','ANE','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Air Niugini','ANG','Papua New Guinea')")
c.execute("INSERT INTO Airlines VALUES ('Air Arabia','ABY','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Air Canada','ACA','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Air Baltic','BTI','Latvia')")
c.execute("INSERT INTO Airlines VALUES ('Air Nippon','ANK','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Airnorth','ANO','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Air North Charter - Canada','ANT','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Air New Zealand','ANZ','New Zealand')")
c.execute("INSERT INTO Airlines VALUES ('Alitalia Express','SMX','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Aero Flight','ARF','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Arrow Air','APW','United States')")
c.execute("INSERT INTO Airlines VALUES ('Aerocondor','ARD','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Aires','ARE',' S.A.')")
c.execute("INSERT INTO Airlines VALUES ('Aerolineas Argentinas','ARG','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Alaska Airlines','ASA','ALASKA')")
c.execute("INSERT INTO Airlines VALUES ('Air Sinai','ASD','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Atlantic Southeast Airlines','ASQ','United States')")
c.execute("INSERT INTO Airlines VALUES ('Astrakhan Airlines','ASZ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Air Tanzania','ATC','Tanzania')")
c.execute("INSERT INTO Airlines VALUES ('Air Burkina','VBW','Burkina Faso')")
c.execute("INSERT INTO Airlines VALUES ('Airlines Of Tasmania','ATM','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Air Saint Pierre','SPM','France')")
c.execute("INSERT INTO Airlines VALUES ('Austrian Airlines','AUA','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Air Southwest','WOW','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Augsburg Airways','AUB','Germany')")
c.execute("INSERT INTO Airlines VALUES ('ATUR','TUR','Ecuador')")
c.execute("INSERT INTO Airlines VALUES ('Abu Dhabi Amiri Flight','AUH','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Aeroflot-Nord','AUL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Aurigny Air Services','AUR','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Austral Lineas Aereas','AUT','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Avianca - Aerovias Nacionales de Colombia','AVA','AVIANCA')")
c.execute("INSERT INTO Airlines VALUES ('Air Vanuatu','AVN','Vanuatu')")
c.execute("INSERT INTO Airlines VALUES ('Air Bangladesh','BGD','Bangladesh')")
c.execute("INSERT INTO Airlines VALUES ('Air Mediterranee','BIE','France')")
c.execute("INSERT INTO Airlines VALUES ('Air Moorea','TAH','France')")
c.execute("INSERT INTO Airlines VALUES ('Aeroline GmbH','AWU','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Air Wales','AWW','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Air Caraïbes','FWI','France')")
c.execute("INSERT INTO Airlines VALUES ('Air India Express','AXB','India')")
c.execute("INSERT INTO Airlines VALUES ('Air Exel','AXL','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('AirAsia','AXM','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('Atlant-Soyuz Airlines','AYZ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Alitalia','AZA','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Amaszonas','AZN','Bolivia')")
c.execute("INSERT INTO Airlines VALUES ('Air Zimbabwe','AZW','Zimbabwe')")
c.execute("INSERT INTO Airlines VALUES ('Aserca Airlines','OCA','Venezuela')")
c.execute("INSERT INTO Airlines VALUES ('Rossiya-Russian Airlines','SDM','Russia')")
c.execute("INSERT INTO Airlines VALUES ('American Eagle Airlines','EGF','United States')")
c.execute("INSERT INTO Airlines VALUES ('AD Aviation','VUE','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Air Ivoire','VUN','Ivory Coast')")
c.execute("INSERT INTO Airlines VALUES ('Air Botswana','BOT','Botswana')")
c.execute("INSERT INTO Airlines VALUES ('Air Foyle','UPA','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Air Tahiti','VTA','French Polynesia')")
c.execute("INSERT INTO Airlines VALUES ('Air VIA','VIM','Bulgaria')")
c.execute("INSERT INTO Airlines VALUES ('Africa West','WTA','Togo')")
c.execute("INSERT INTO Airlines VALUES ('ATRAN Cargo Airlines','VAS','Russian Federation')")
c.execute("INSERT INTO Airlines VALUES ('Air China','CCA','China')")
c.execute("INSERT INTO Airlines VALUES ('Aero Condor Peru','CDP','Peru')")
c.execute("INSERT INTO Airlines VALUES ('Air Chathams','CVA','New Zealand')")
c.execute("INSERT INTO Airlines VALUES ('Air Marshall Islands','CWM','Marshall Islands')")
c.execute("INSERT INTO Airlines VALUES ('Access Air','CYD','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Algerie','DAH','Algeria')")
c.execute("INSERT INTO Airlines VALUES ('Adam Air','DHI','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Air Dolomiti','DLA','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Aeroflot-Don','DNV','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Air Madrid','DRD','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Aer Lingus','EIN','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('Air Finland','FIF','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Airfix Aviation','FIX','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Air Pacific','FJI','Fiji')")
c.execute("INSERT INTO Airlines VALUES ('Atlantic Airways','FLI','Faroe Islands')")
c.execute("INSERT INTO Airlines VALUES ('Air Florida','FLZ','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Iceland','FXI','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Air Philippines','GAP','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Air Guinee Express','GIP','Guinea')")
c.execute("INSERT INTO Airlines VALUES ('Air Greenland','GRL','Denmark')")
c.execute("INSERT INTO Airlines VALUES ('Atlas Air','GTI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Guyane','GUY','French Guiana')")
c.execute("INSERT INTO Airlines VALUES ('Air Bagan','JAB','Myanmar')")
c.execute("INSERT INTO Airlines VALUES ('Air Canada Jazz','JZA','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Atlasjet','KKK','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Air Koryo','KOR','Democratic Peoples Republic of Korea')")
c.execute("INSERT INTO Airlines VALUES ('Air Astana','KZR','Kazakhstan')")
c.execute("INSERT INTO Airlines VALUES ('Albanian Airlines','LBC','Albania')")
c.execute("INSERT INTO Airlines VALUES ('Air Alfa','LFA','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Aerolane','LNE','Ecuador')")
c.execute("INSERT INTO Airlines VALUES ('Atlantis European Airways','LUR','Armenia')")
c.execute("INSERT INTO Airlines VALUES ('Air Luxor','LXR','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Air Mauritius','MAU','Mauritius')")
c.execute("INSERT INTO Airlines VALUES ('Air Madagascar','MDG','Madagascar')")
c.execute("INSERT INTO Airlines VALUES ('Air Moldova','MLD','Moldova')")
c.execute("INSERT INTO Airlines VALUES ('Air Plus Comet','MPD','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Aero Contractors','NIG','Nigeria')")
c.execute("INSERT INTO Airlines VALUES ('Aeropelican Air Services','PEL','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Aer Arann','REA','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('Air Austral','REU','France')")
c.execute("INSERT INTO Airlines VALUES ('Asian Spirit','RIT','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Air Afrique','RKA','Ivory Coast')")
c.execute("INSERT INTO Airlines VALUES ('Airlinair','RLA','France')")
c.execute("INSERT INTO Airlines VALUES ('Aero Lanka','RLN','Sri Lanka')")
c.execute("INSERT INTO Airlines VALUES ('Air Salone','RNE','Sierra Leone')")
c.execute("INSERT INTO Airlines VALUES ('Armavia','RNV','Armenia')")
c.execute("INSERT INTO Airlines VALUES ('AeroRep','RPB','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Aero-Service','RSR','Republic of the Congo')")
c.execute("INSERT INTO Airlines VALUES ('Aerosur','RSU','Bolivia')")
c.execute("INSERT INTO Airlines VALUES ('Aeronorte','RTE','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Avient Aviation','SMJ','Zimbabwe')")
c.execute("INSERT INTO Airlines VALUES ('Aircompany Yakutia','SYL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Aeromar','TAO','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('Arkefly','TFL','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('Airlines PNG','TOK','Papua New Guinea')")
c.execute("INSERT INTO Airlines VALUES ('AirTran Airways','TRS','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Transat','TSC','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Avialeasing Aviation Company','TWN','Uzbekistan')")
c.execute("INSERT INTO Airlines VALUES ('Tyrolean Airways','TYR','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Aerolineas Galapagos (Aerogal)','GLG','Ecuador')")
c.execute("INSERT INTO Airlines VALUES ('Alrosa Mirny Air Enterprise','DRU','Russia')")
c.execute("INSERT INTO Airlines VALUES ('British Airways','BAW','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Biman Bangladesh Airlines','BBC','Bangladesh')")
c.execute("INSERT INTO Airlines VALUES ('Belair Airlines','BHP','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Bahamasair','BHS','Bahamas')")
c.execute("INSERT INTO Airlines VALUES ('British International Helicopters','BIH','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('BF-Lento OY','BKF','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Bangkok Airways','BKP','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Blue1','BLF','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Baltic Airlines','BLL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Bearskin Lake Air Service','BLS','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Bellview Airlines','BLV','Nigeria')")
c.execute("INSERT INTO Airlines VALUES ('bmi','BMA','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('bmibaby','BMI','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Bemidji Airlines','BMJ','United States')")
c.execute("INSERT INTO Airlines VALUES ('British Midland Regional','BMR','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Blue Panorama Airlines','BPA','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Budapest Aircraft Services/Manx2','BPS','Hungary')")
c.execute("INSERT INTO Airlines VALUES ('Bering Air','BRG','United States')")
c.execute("INSERT INTO Airlines VALUES ('Brazilian Air Force','BRS','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Belavia Belarusian Airlines','BRU','Belarus')")
c.execute("INSERT INTO Airlines VALUES ('Metro Batavia','BTV','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Berjaya Air','BVT','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('Blue Wings','BWG','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Brit Air','BZH','France')")
c.execute("INSERT INTO Airlines VALUES ('Brussels Airlines','DAT','Belgium')")
c.execute("INSERT INTO Airlines VALUES ('Binter Canarias','IBB','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Blue Air','JOR','Romania')")
c.execute("INSERT INTO Airlines VALUES ('British Mediterranean Airways','LAJ','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Bulgaria Air','LZB','Bulgaria')")
c.execute("INSERT INTO Airlines VALUES ('Barents AirLink','NKF','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('CAL Cargo Air Lines','ICL','Israel')")
c.execute("INSERT INTO Airlines VALUES ('Calima Aviacion','CLI','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Canadian Airlines','CDN','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Canadian North','MPE','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Cape Air','KAP','United States')")
c.execute("INSERT INTO Airlines VALUES ('Caribbean Airlines','BWA','Trinidad and Tobago')")
c.execute("INSERT INTO Airlines VALUES ('Carpatair','KRP','Romania')")
c.execute("INSERT INTO Airlines VALUES ('Caspian Airlines','CPN','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Cathay Pacific','CPA','Hong Kong SAR of China')")
c.execute("INSERT INTO Airlines VALUES ('Cayman Airways','CAY','Cayman Islands')")
c.execute("INSERT INTO Airlines VALUES ('Cebu Pacific','CEB','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Central Connect Airlines','CCG','Czech Republic')")
c.execute("INSERT INTO Airlines VALUES ('Centralwings','CLW','Poland')")
c.execute("INSERT INTO Airlines VALUES ('Charter Air','CHW','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Chautauqua Airlines','CHQ','United States')")
c.execute("INSERT INTO Airlines VALUES ('China Airlines','CAL','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('China Eastern Airlines','CES','China')")
c.execute("INSERT INTO Airlines VALUES ('China Southern Airlines','CSN','China')")
c.execute("INSERT INTO Airlines VALUES ('China United Airlines','CUA','China')")
c.execute("INSERT INTO Airlines VALUES ('Yunnan Airlines','CYH','China')")
c.execute("INSERT INTO Airlines VALUES ('Cimber Air','CIM','Denmark')")
c.execute("INSERT INTO Airlines VALUES ('Cirrus Airlines','RUS','Germany')")
c.execute("INSERT INTO Airlines VALUES ('City Airline','SDR','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('City Connexion Airlines','CIX','Burundi')")
c.execute("INSERT INTO Airlines VALUES ('CityJet','BCY','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('BA CityFlyer','CFE','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Click Airways','CGK','Kyrgyzstan')")
c.execute("INSERT INTO Airlines VALUES ('Colgan Air','CJC','United States')")
c.execute("INSERT INTO Airlines VALUES ('Comair','COM','United States')")
c.execute("INSERT INTO Airlines VALUES ('Comair','CAW','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('CommutAir','UCA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Comores Airlines','CWK','Comoros')")
c.execute("INSERT INTO Airlines VALUES ('Compass Airlines','CPZ','United States')")
c.execute("INSERT INTO Airlines VALUES ('Condor Flugdienst','CFG','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Consorcio Aviaxsa','CHP','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('Contact Air','KIS','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Continental Airlines','COA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Continental Micronesia','CMI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Conviasa','VCV','Venezuela')")
c.execute("INSERT INTO Airlines VALUES ('Copa Airlines','CMP','Panama')")
c.execute("INSERT INTO Airlines VALUES ('Copterline','AAQ','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Corendon Airlines','CAI','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Corsairfly','CRL','France')")
c.execute("INSERT INTO Airlines VALUES ('Corse-Mediterranee','CCM','France')")
c.execute("INSERT INTO Airlines VALUES ('Crest Aviation','CAN','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Croatia Airlines','CTN','Croatia')")
c.execute("INSERT INTO Airlines VALUES ('Crown Airways','CRO','United States')")
c.execute("INSERT INTO Airlines VALUES ('Cubana de Aviación','CUB','Cuba')")
c.execute("INSERT INTO Airlines VALUES ('Cyprus Airways','CYP','Cyprus')")
c.execute("INSERT INTO Airlines VALUES ('Czech Airlines','CSA','Czech Republic')")
c.execute("INSERT INTO Airlines VALUES ('DAT Danish Air Transport','DTR','Denmark')")
c.execute("INSERT INTO Airlines VALUES ('Daallo Airlines','DAO','Djibouti')")
c.execute("INSERT INTO Airlines VALUES ('Dalavia','KHB','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Darwin Airline','DWT','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Delta Aerotaxi','DEA','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Delta Air Lines','DAL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Denim Air','DNM','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('Djibouti Airlines','DJB','Djibouti')")
c.execute("INSERT INTO Airlines VALUES ('Dniproavia','UDN','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Dominicana de Aviaci','DOA','Dominican Republic')")
c.execute("INSERT INTO Airlines VALUES ('Domodedovo Airlines','DMO','Russia')")
c.execute("INSERT INTO Airlines VALUES ('DonbassAero','UDC','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Dragonair','HDA','DRAGON')")
c.execute("INSERT INTO Airlines VALUES ('Druk Air','DRK','Bhutan')")
c.execute("INSERT INTO Airlines VALUES ('Dubrovnik Air','DBK','Croatia')")
c.execute("INSERT INTO Airlines VALUES ('Dutch Antilles Express','DNL','Netherlands Antilles')")
c.execute("INSERT INTO Airlines VALUES ('dba','BAG','Germany')")
c.execute("INSERT INTO Airlines VALUES ('EVA Air','EVA','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('East African','UGX','Uganda')")
c.execute("INSERT INTO Airlines VALUES ('Eastern Airways','EZE','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Eastland Air','ELA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Ecuavia','ECU','Ecuador')")
c.execute("INSERT INTO Airlines VALUES ('Edelweiss Air','EDW','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Egyptair','MSR','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('El Al Israel Airlines','ELY','Israel')")
c.execute("INSERT INTO Airlines VALUES ('El-Buraq Air Transport','BRQ','Libya')")
c.execute("INSERT INTO Airlines VALUES ('Emirates','UAE','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Empresa Ecuatoriana De Aviacion','EEA','Ecuador')")
c.execute("INSERT INTO Airlines VALUES ('Eritrean Airlines','ERT','Eritrea')")
c.execute("INSERT INTO Airlines VALUES ('Estonian Air','ELL','Estonia')")
c.execute("INSERT INTO Airlines VALUES ('Ethiopian Airlines','ETH','Ethiopia')")
c.execute("INSERT INTO Airlines VALUES ('Etihad Airways','ETD','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Eurocypria Airlines','ECA','Cyprus')")
c.execute("INSERT INTO Airlines VALUES ('Eurofly Service','EEU','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Eurolot','ELO','Poland')")
c.execute("INSERT INTO Airlines VALUES ('European Air Express','EAL','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Eurowings','EWG','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Evergreen International Airlines','EIA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Excel Airways','XLA','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Excel Charter','XEL','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Express One International','LHN','United States')")
c.execute("INSERT INTO Airlines VALUES ('ExpressJet','BTA','United States')")
c.execute("INSERT INTO Airlines VALUES ('easyJet','EZY','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Far Eastern Air Transport','EFA','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('Finnair','FIN','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Finncomm Airlines','WBA','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Firefly','FFM','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('First Air','FAB','Canada')")
c.execute("INSERT INTO Airlines VALUES ('First Choice Airways','FCA','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Flightline','FLT','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Florida West International Airways','FWL','United States')")
c.execute("INSERT INTO Airlines VALUES ('AirAsia X','XAX','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('FlyLal','LIL','Lithuania')")
c.execute("INSERT INTO Airlines VALUES ('FlyNordic','NDC','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Flybaboo','BBO','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Flybe','BEE','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Flyglobespan','GSM','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Flyhy Cargo Airlines','FYH','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Formosa Airlines','FOS','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('Freedom Air','FRE','United States')")
c.execute("INSERT INTO Airlines VALUES ('Freedom Airlines','FRL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Frontier Airlines','FFT','United States')")
c.execute("INSERT INTO Airlines VALUES ('Frontier Flying Service','FTA','United States')")
c.execute("INSERT INTO Airlines VALUES ('GB Airways','GBL','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Garuda Indonesia','GIA','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Gazpromavia','GZP','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Georgian Airways','TGZ','Georgia')")
c.execute("INSERT INTO Airlines VALUES ('Georgian National Airlines','GFG','Georgia')")
c.execute("INSERT INTO Airlines VALUES ('Germania','GMI','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Germanwings','GWI','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Ghana International Airlines','GHB','Ghana')")
c.execute("INSERT INTO Airlines VALUES ('Go Air','GOW','India')")
c.execute("INSERT INTO Airlines VALUES ('GoJet Airlines','GJS','United States')")
c.execute("INSERT INTO Airlines VALUES ('Gol Transportes Aéreos','GLO','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Golden Air','GAO','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Great Lakes Airlines','GLA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Grupo TACA','TAT','Costa Rica')")
c.execute("INSERT INTO Airlines VALUES ('Gulf Air','GFA','Oman')")
c.execute("INSERT INTO Airlines VALUES ('Gulf Air Bahrain','GBA','Bahrain')")
c.execute("INSERT INTO Airlines VALUES ('Gulfstream International Airlines','GFT','United States')")
c.execute("INSERT INTO Airlines VALUES ('Hageland Aviation Services','HAG','United States')")
c.execute("INSERT INTO Airlines VALUES ('Hainan Airlines','CHH','China')")
c.execute("INSERT INTO Airlines VALUES ('Haiti Ambassador Airlines','HAM','Haiti')")
c.execute("INSERT INTO Airlines VALUES ('Hamburg International','HHI','Germany')")
c.execute("INSERT INTO Airlines VALUES ('TUIfly','HLX','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Hapagfly','HLF','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Hawaiian Airlines','HAL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Heli France','HFR','France')")
c.execute("INSERT INTO Airlines VALUES ('Helijet','JBA','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Hellas Jet','HEJ','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Hello','FHE','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Helvetic Airways','OAW','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Highland Airways','HWY','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Hokkaido International Airlines','ADO','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Hong Kong Airlines','CRK','Hong Kong SAR of China')")
c.execute("INSERT INTO Airlines VALUES ('Hong Kong Express Airways','HKE','Hong Kong SAR of China')")
c.execute("INSERT INTO Airlines VALUES ('Horizon Air','QXE','United States')")
c.execute("INSERT INTO Airlines VALUES ('Horizon Airlines','HZA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Iberia Airlines','IBE','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Iberworld','IWD','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Ibex Airlines','IBX','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Icar Air','RAC','Bosnia and Herzegovina')")
c.execute("INSERT INTO Airlines VALUES ('Icelandair','ICE','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Imair Airlines','ITX','Azerbaijan')")
c.execute("INSERT INTO Airlines VALUES ('IndiGo Airlines','IGO','India')")
c.execute("INSERT INTO Airlines VALUES ('Indian Airlines','IAC','India')")
c.execute("INSERT INTO Airlines VALUES ('Indigo','IBU','United States')")
c.execute("INSERT INTO Airlines VALUES ('Indonesia AirAsia','AWQ','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Indonesian Airlines','IAA','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Interair South Africa','ILN','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Interavia Airlines','SUW','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Interlink Airlines','ITK','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Intersky','ISK','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Iran Air','IRA','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Iran Aseman Airlines','IRC','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Iraqi Airways','IAW','Iraq')")
c.execute("INSERT INTO Airlines VALUES ('Cargo Plus Aviation','CGP','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Islas Airways','ISW','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Islena De Inversiones','ISV','Honduras')")
c.execute("INSERT INTO Airlines VALUES ('Israir','ISR','Israel')")
c.execute("INSERT INTO Airlines VALUES ('Itek Air','IKA','Kyrgyzstan')")
c.execute("INSERT INTO Airlines VALUES ('JAL Express','JEX','Japan')")
c.execute("INSERT INTO Airlines VALUES ('JALways','JAZ','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Japan Airlines','JAL','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Japan Asia Airways','JAA','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Japan Transocean Air','JTA','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Jazeera Airways','JZR','Kuwait')")
c.execute("INSERT INTO Airlines VALUES ('Jeju Air','JJA','Republic of Korea')")
c.execute("INSERT INTO Airlines VALUES ('Jet Airways','JAI','India')")
c.execute("INSERT INTO Airlines VALUES ('Jetstar Asia Airways','JSA','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Jet2.com','EXS','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Jet4You','JFU','Morocco')")
c.execute("INSERT INTO Airlines VALUES ('JetBlue Airways','JBU','United States')")
c.execute("INSERT INTO Airlines VALUES ('Jetairfly','JAF','Belgium')")
c.execute("INSERT INTO Airlines VALUES ('Jetflite','JEF','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Jetstar Airways','JST','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Juneyao Airlines','DKH','China')")
c.execute("INSERT INTO Airlines VALUES ('KD Avia','KNI','Russia')")
c.execute("INSERT INTO Airlines VALUES ('KLM Cityhopper','KLC','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('KLM Royal Dutch Airlines','KLM','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('Kam Air','KMF','Afghanistan')")
c.execute("INSERT INTO Airlines VALUES ('Kavminvodyavia','MVD','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Kendell Airlines','KDA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Kenmore Air','KEN','United States')")
c.execute("INSERT INTO Airlines VALUES ('Kenya Airways','KQA','Kenya')")
c.execute("INSERT INTO Airlines VALUES ('Kingfisher Airlines','KFR','India')")
c.execute("INSERT INTO Airlines VALUES ('Kish Air','IRK','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Kogalymavia Air Company','KGL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Korean Air','KAL','Republic of Korea')")
c.execute("INSERT INTO Airlines VALUES ('Kosmos','KSM','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Krasnojarsky Airlines','KJC','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Kuban Airlines','KIL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Kuwait Airways','KAC','Kuwait')")
c.execute("INSERT INTO Airlines VALUES ('Kuzu Airlines Cargo','KZU','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('LACSA','LRC','Costa Rica')")
c.execute("INSERT INTO Airlines VALUES ('LAN Airlines','LAN','Chile')")
c.execute("INSERT INTO Airlines VALUES ('LAN Argentina','DSM','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('LAN Express','LXP','Chile')")
c.execute("INSERT INTO Airlines VALUES ('LAN Peru','LPE','Peru')")
c.execute("INSERT INTO Airlines VALUES ('LOT Polish Airlines','LOT','Poland')")
c.execute("INSERT INTO Airlines VALUES ('LTE International Airways','LTE','Spain')")
c.execute("INSERT INTO Airlines VALUES ('LTU Austria','LTO','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Lao Airlines','LAO','Lao Peoples Democratic Republic')")
c.execute("INSERT INTO Airlines VALUES ('LatCharter','LTC','Latvia')")
c.execute("INSERT INTO Airlines VALUES ('Lauda Air','LDA','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Leeward Islands Air Transport','LIA','Antigua and Barbuda')")
c.execute("INSERT INTO Airlines VALUES ('Libyan Arab Airlines','LAA','Libya')")
c.execute("INSERT INTO Airlines VALUES ('Linhas A','LAM','Mozambique')")
c.execute("INSERT INTO Airlines VALUES ('Lion Mentari Airlines','LNI','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Luftfahrtgesellschaft Walter','LGW','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Lufthansa','DLH','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Lufthansa Cargo','GEC','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Lufthansa CityLine','CLH','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Lufttransport','LTR','Norway')")
c.execute("INSERT INTO Airlines VALUES ('Luxair','LGL','Luxembourg')")
c.execute("INSERT INTO Airlines VALUES ('L','LPR','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('MasAir','MAA','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('MAT Macedonian Airlines','MAK','Macedonia')")
c.execute("INSERT INTO Airlines VALUES ('MIAT Mongolian Airlines','MGL','Mongolia')")
c.execute("INSERT INTO Airlines VALUES ('MNG Airlines','MNB','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Macair Airlines','MCK','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Mahan Air','IRM','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Malaysia Airlines','MAS','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('Malmo Aviation','SCW','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Malta Air Charter','MAC','Malta')")
c.execute("INSERT INTO Airlines VALUES ('Malév','MAH','Hungary')")
c.execute("INSERT INTO Airlines VALUES ('Mandala Airlines','MDL','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Mandarin Airlines','MDA','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('Mango','MNO','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Martinair','MPH','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('Maxair','MXL','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Maya Island Air','MYD','Belize')")
c.execute("INSERT INTO Airlines VALUES ('Meridiana','ISS','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Merpati Nusantara Airlines','MNA','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Mesa Airlines','ASH','United States')")
c.execute("INSERT INTO Airlines VALUES ('Mesaba Airlines','MES','United States')")
c.execute("INSERT INTO Airlines VALUES ('Mexicana de Aviaci','MXA','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('Middle East Airlines','MEA','Lebanon')")
c.execute("INSERT INTO Airlines VALUES ('Midway Airlines','MDW','United States')")
c.execute("INSERT INTO Airlines VALUES ('Midwest Airlines','MEP','United States')")
c.execute("INSERT INTO Airlines VALUES ('Midwest Airlines (Egypt)','MWA','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Moldavian Airlines','MDV','Moldova')")
c.execute("INSERT INTO Airlines VALUES ('Monarch Airlines','MON','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Montenegro Airlines','MGX','Montenegro')")
c.execute("INSERT INTO Airlines VALUES ('Morningstar Air Express','MAL','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Moskovia Airlines','GAI','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Motor Sich','MSI','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('MyTravel Airways','MYT','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Myanma Airways','UBA','Myanmar')")
c.execute("INSERT INTO Airlines VALUES ('Myanmar Airways International','MMM','Myanmar')")
c.execute("INSERT INTO Airlines VALUES ('Myflug','MYA','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Nasair','NAS','Eritrea')")
c.execute("INSERT INTO Airlines VALUES ('National Jet Systems','NJS','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Nationwide Airlines','NTW','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Nauru Air Corporation','RON','Nauru')")
c.execute("INSERT INTO Airlines VALUES ('Nepal Airlines','RNA','Nepal')")
c.execute("INSERT INTO Airlines VALUES ('NetJets','EJA','United States')")
c.execute("INSERT INTO Airlines VALUES ('New England Airlines','NEA','United States')")
c.execute("INSERT INTO Airlines VALUES ('NextJet','NTJ','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Niki','NLY','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Nok Air','NOK','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Norfolk County Flight College','NCF','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('North American Airlines','NTM','Canada')")
c.execute("INSERT INTO Airlines VALUES ('North American Charters','HMR','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Northwest Airlines','NWA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Northwestern Air','PLR','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Norwegian Air Shuttle','NAX','Norway')")
c.execute("INSERT INTO Airlines VALUES ('Norwegian Aviation College','TFN','Norway')")
c.execute("INSERT INTO Airlines VALUES ('Nouvel Air Tunisie','LBT','Tunisia')")
c.execute("INSERT INTO Airlines VALUES ('Novair','NVR','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Nas Air','KNE','Saudi Arabia')")
c.execute("INSERT INTO Airlines VALUES ('Oasis Hong Kong Airlines','OHK','Hong Kong')")
c.execute("INSERT INTO Airlines VALUES ('Ocean Air','BCN','Mauritania')")
c.execute("INSERT INTO Airlines VALUES ('Oceanair','ONE','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Olympic Airlines','OAL','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Oman Air','OMA','Oman')")
c.execute("INSERT INTO Airlines VALUES ('Omni Air International','OAE','United States')")
c.execute("INSERT INTO Airlines VALUES ('One Two Go Airlines','OTG','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Onur Air','OHY','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Orenburg Airlines','ORB','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Orient Thai Airlines','OEA','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Origin Pacific Airways','OGN','New Zealand')")
c.execute("INSERT INTO Airlines VALUES ('Ostfriesische Lufttransport','OLT','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Overland Airways','OLA','Nigeria')")
c.execute("INSERT INTO Airlines VALUES ('Ozjet Airlines','OZJ','Australia')")
c.execute("INSERT INTO Airlines VALUES ('PAN Air','PNR','Spain')")
c.execute("INSERT INTO Airlines VALUES ('PB Air','PBA','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('PLUNA','PUA','Uruguay')")
c.execute("INSERT INTO Airlines VALUES ('PMTair','PMT','Cambodia')")
c.execute("INSERT INTO Airlines VALUES ('Jetstar Pacific','PIC','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('Pacific Coastal Airline','PCO','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Pacific East Asia Cargo Airlines','PEC','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Pacific Island Aviation','PSA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Pacific Wings','NMI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Pakistan International Airlines','PIA','Pakistan')")
c.execute("INSERT INTO Airlines VALUES ('Paramount Airways','PMW','India')")
c.execute("INSERT INTO Airlines VALUES ('Passaredo Transportes Aereos','PTB','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Pegasus Airlines','PGT','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Peninsula Airways','PEN','United States')")
c.execute("INSERT INTO Airlines VALUES ('Philippine Airlines','PAL','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Piedmont Airlines (1948-1989)','PDT','United States')")
c.execute("INSERT INTO Airlines VALUES ('Pinnacle Airlines','FLG','United States')")
c.execute("INSERT INTO Airlines VALUES ('Polet','POT','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Polynesian Airlines','PAO','Samoa')")
c.execute("INSERT INTO Airlines VALUES ('Porter Airlines','POE','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Portugalia','PGA','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Potomac Air','PDC','United States')")
c.execute("INSERT INTO Airlines VALUES ('Precision Air','PRF','Tanzania')")
c.execute("INSERT INTO Airlines VALUES ('Privatair','PTI','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Qantas','QFA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Qatar Airways','QTR','Qatar')")
c.execute("INSERT INTO Airlines VALUES ('Kinloss Flying Training Unit','KIN','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Regional Express','RXA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Republic Airlines','RPA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Republic Express Airlines','RPH','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Air Rarotonga','RAR','Cook Islands')")
c.execute("INSERT INTO Airlines VALUES ('Royal Air Maroc','RAM','Morocco')")
c.execute("INSERT INTO Airlines VALUES ('Royal Brunei Airlines','RBA','Brunei')")
c.execute("INSERT INTO Airlines VALUES ('Royal Jordanian','RJA','Jordan')")
c.execute("INSERT INTO Airlines VALUES ('Rusline','RLU','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Rwandair Express','RWD','Rwanda')")
c.execute("INSERT INTO Airlines VALUES ('Ryan Air Services','RYA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Ryan International Airlines','RYN','United States')")
c.execute("INSERT INTO Airlines VALUES ('Ryanair','RYR','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('Régional','RAE','France')")
c.execute("INSERT INTO Airlines VALUES ('SATA International','RZO','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('South African Airways','SAA','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Shaheen Air International','SAI','Pakistan')")
c.execute("INSERT INTO Airlines VALUES ('Scandinavian Airlines System','SAS','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('ScotAirways','SAY','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('S7 Airlines','SBI','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Seaborne Airlines','SBS','United States')")
c.execute("INSERT INTO Airlines VALUES ('Scenic Airlines','SCE','United States')")
c.execute("INSERT INTO Airlines VALUES ('SriLankan Airlines','ALK','Sri Lanka')")
c.execute("INSERT INTO Airlines VALUES ('Sun Country Airlines','SCX','United States')")
c.execute("INSERT INTO Airlines VALUES ('Southeast Air','SEA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Sky Express','SEH','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Spicejet','SEJ','India')")
c.execute("INSERT INTO Airlines VALUES ('Star Flyer','SFJ','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Skagway Air Service','SGY','United States')")
c.execute("INSERT INTO Airlines VALUES ('Sahara Airlines','SHD','Algeria')")
c.execute("INSERT INTO Airlines VALUES ('SATA Air Acores','SAT','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Singapore Airlines','SIA','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Sibaviatrans','SIB','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Skynet Airlines','SIH','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('Sriwijaya Air','SJY','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Sama Airlines','SMY','Saudi Arabia')")
c.execute("INSERT INTO Airlines VALUES ('Singapore Airlines Cargo','SQC','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Siem Reap Airways','SRH','Cambodia')")
c.execute("INSERT INTO Airlines VALUES ('South East Asian Airlines','SRQ','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Skyservice Airlines','SSV','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Servicios de Transportes A','STU','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Sudan Airways','SUD','Sudan')")
c.execute("INSERT INTO Airlines VALUES ('Saudi Arabian Airlines','SVA','Saudi Arabia')")
c.execute("INSERT INTO Airlines VALUES ('Southwest Airlines','SWA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Southern Winds Airlines','SWD','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Swiss International Air Lines','SWR','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Swiss European Air Lines','SWU','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Swe Fly','SWV','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('SunExpress','SXS','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Syrian Arab Airlines','SYR','Syrian Arab Republic')")
c.execute("INSERT INTO Airlines VALUES ('Skywalk Airlines','SYX','United States')")
c.execute("INSERT INTO Airlines VALUES ('Shandong Airlines','CDG','China')")
c.execute("INSERT INTO Airlines VALUES ('SAS Braathens','CNO','Norway')")
c.execute("INSERT INTO Airlines VALUES ('Spring Airlines','CQH','China')")
c.execute("INSERT INTO Airlines VALUES ('Sichuan Airlines','CSC','China')")
c.execute("INSERT INTO Airlines VALUES ('Shanghai Airlines','CSH','China')")
c.execute("INSERT INTO Airlines VALUES ('Shenzhen Airlines','CSZ','China')")
c.execute("INSERT INTO Airlines VALUES ('SkyEurope','ESK','Slovakia')")
c.execute("INSERT INTO Airlines VALUES ('Sky Europe Airlines','HSK','Slovakia')")
c.execute("INSERT INTO Airlines VALUES ('Spanair','JKK','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Spirit Airlines','NKS','United States')")
c.execute("INSERT INTO Airlines VALUES ('SATENA','NSE','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Skywest Airlines','OZW','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Santa Barbara Airlines','BBR','Venezuela')")
c.execute("INSERT INTO Airlines VALUES ('Sky Airline','SKU','Chile')")
c.execute("INSERT INTO Airlines VALUES ('SkyWest','SKW','United States')")
c.execute("INSERT INTO Airlines VALUES ('Skyways Express','SKX','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Skymark Airlines','SKY','Japan')")
c.execute("INSERT INTO Airlines VALUES ('SilkAir','SLK','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Surinam Airways','SLM','Suriname')")
c.execute("INSERT INTO Airlines VALUES ('Sterling Airlines','SNB','Denmark')")
c.execute("INSERT INTO Airlines VALUES ('Skynet Asia Airways','SNJ','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Solomon Airlines','SOL','Solomon Islands')")
c.execute("INSERT INTO Airlines VALUES ('Southern Airways','SOU','United States')")
c.execute("INSERT INTO Airlines VALUES ('Saratov Aviation Division','SOV','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Sat Airlines','SOZ','Kazakhstan')")
c.execute("INSERT INTO Airlines VALUES ('South Pacific Island Airways','SPI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Shuttle America','TCF','United States')")
c.execute("INSERT INTO Airlines VALUES ('Scat Air','VSV','Kazakhstan')")
c.execute("INSERT INTO Airlines VALUES ('TAME','TAE','Ecuador')")
c.execute("INSERT INTO Airlines VALUES ('TAM Brazilian Airlines','TAM','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('TAP Portugal','TAP','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Tunisair','TAR','Tunisia')")
c.execute("INSERT INTO Airlines VALUES ('Thai Air Cargo','TCG','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Thomas Cook Airlines','TCW','Belgium')")
c.execute("INSERT INTO Airlines VALUES ('Thomas Cook Airlines','TCX','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Trigana Air Service','TGN','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Tiger Airways','TGW','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Thai Airways International','THA','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Turk Hava Kurumu Hava Taksi Isletmesi','THK','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Thai AirAsia','AIQ','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Turkish Airlines','THY','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Tajikistan International Airlines','TIL','Tajikistan')")
c.execute("INSERT INTO Airlines VALUES ('Twin Jet','TJT','France')")
c.execute("INSERT INTO Airlines VALUES ('Translift Airways','TLA','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('Trans Mediterranean Airlines','TMA','Lebanon')")
c.execute("INSERT INTO Airlines VALUES ('Tiara Air','TNM','Aruba')")
c.execute("INSERT INTO Airlines VALUES ('Thomsonfly','TOM','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Tropic Air','TOS','Belize')")
c.execute("INSERT INTO Airlines VALUES ('TAMPA','TPA','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('TransAsia Airways','TNA','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('Transavia Holland','TRA','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('TACV','TCV','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Transwest Air','ABS','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Transaero Airlines','TSO','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Turkmenistan Airlines','TUA','Turkmenistan')")
c.execute("INSERT INTO Airlines VALUES ('Tuninter','TUI','Tunisia')")
c.execute("INSERT INTO Airlines VALUES ('Travel Service','TVS','Czech Republic')")
c.execute("INSERT INTO Airlines VALUES ('TUIfly Nordic','BLX','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('TAAG Angola Airlines','DTA','Angola')")
c.execute("INSERT INTO Airlines VALUES ('Turkish Air Force','HVK','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('TAM Mercosur','LAP','Paraguay')")
c.execute("INSERT INTO Airlines VALUES ('Trans States Airlines','LOF','United States')")
c.execute("INSERT INTO Airlines VALUES ('Tarom','ROT','Romania')")
c.execute("INSERT INTO Airlines VALUES ('Turan Air','URN','Azerbaijan')")
c.execute("INSERT INTO Airlines VALUES ('TRIP Linhas A','TIB','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('USA3000 Airlines','GWY','United States')")
c.execute("INSERT INTO Airlines VALUES ('United Airlines','UAL','United States')")
c.execute("INSERT INTO Airlines VALUES ('United Air Charters','UAC','Zimbabwe')")
c.execute("INSERT INTO Airlines VALUES ('Ural Airlines','SVR','Russia')")
c.execute("INSERT INTO Airlines VALUES ('UM Airlines','UKM','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('US Airways','USA','United States')")
c.execute("INSERT INTO Airlines VALUES ('US Helicopter','USH','United States')")
c.execute("INSERT INTO Airlines VALUES ('UTair Aviation','UTA','Russia')")
c.execute("INSERT INTO Airlines VALUES ('United States Air Force','AIO','United States')")
c.execute("INSERT INTO Airlines VALUES ('Uzbekistan Airways','UZB','Uzbekistan')")
c.execute("INSERT INTO Airlines VALUES ('Ukraine International Airlines','AUI','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Valuair','VLU','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Vasco Air','VFC','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('Vietnam Airlines','HVN','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('VIM Airlines','MOV','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Volaris','VOI','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('Volga-Dnepr Airlines','VDA','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Virgin America','VRD','United States')")
c.execute("INSERT INTO Airlines VALUES ('Virgin Express','VEX','Belgium')")
c.execute("INSERT INTO Airlines VALUES ('Virgin Nigeria Airways','VGN','Nigeria')")
c.execute("INSERT INTO Airlines VALUES ('Virgin Atlantic Airways','VIR','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Viva Macau','VVM','Macao')")
c.execute("INSERT INTO Airlines VALUES ('Volare Airlines','VLE','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Vueling Airlines','VLG','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Vladivostok Air','VLK','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Varig Log','VLO','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Virgin Australia','VOZ','Australia')")
c.execute("INSERT INTO Airlines VALUES ('VRG Linhas Aereas','VRN','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('VASP','VSP','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('VLM Airlines','VLM','Belgium')")
c.execute("INSERT INTO Airlines VALUES ('WebJet Linhas A','WEB','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Welcome Air','WLC','Austria')")
c.execute("INSERT INTO Airlines VALUES ('WestJet','WJA','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Western Airlines','WAL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Widerøe','WIF','Norway')")
c.execute("INSERT INTO Airlines VALUES ('Wind Jet','JET','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Wings Air','WON','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Wizz Air','WZZ','Hungary')")
c.execute("INSERT INTO Airlines VALUES ('Wizz Air Hungary','WVL','Bulgaria')")
c.execute("INSERT INTO Airlines VALUES ('World Airways','WOA','United States')")
c.execute("INSERT INTO Airlines VALUES ('XL Airways France','SEU','France')")
c.execute("INSERT INTO Airlines VALUES ('Xiamen Airlines','CXA','China')")
c.execute("INSERT INTO Airlines VALUES ('Yamal Airlines','LLM','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Yemenia','IYE','Yemen')")
c.execute("INSERT INTO Airlines VALUES ('Yuzhmashavia','UMK','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Zanair','TAN','Tanzania')")
c.execute("INSERT INTO Airlines VALUES ('Zoom Airlines','OOM','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Sky Express','SXR','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Air Busan','ABL','Republic of Korea')")
c.execute("INSERT INTO Airlines VALUES ('Globus','GLP','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Air Kazakhstan','KZK','Kazakhstan')")
c.execute("INSERT INTO Airlines VALUES ('Japan Air System','JAS','Japan')")
c.execute("INSERT INTO Airlines VALUES ('United Airways','UBD','Bangladesh')")
c.execute("INSERT INTO Airlines VALUES ('Fly540','FFV','Kenya')")
c.execute("INSERT INTO Airlines VALUES ('Transavia France','TVF','France')")
c.execute("INSERT INTO Airlines VALUES ('Island Air (WP)','MKU','United States')")
c.execute("INSERT INTO Airlines VALUES ('Uni Air','UIA','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('Red Wings','RWZ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Felix Airways','FXX','Yemen')")
c.execute("INSERT INTO Airlines VALUES ('Kostromskie avialinii','KOQ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Greenfly','GFY','Spain')")
c.execute("INSERT INTO Airlines VALUES ('ELK Airways','ELK','Estonia')")
c.execute("INSERT INTO Airlines VALUES ('Gabon Airlines','GBK','Gabon')")
c.execute("INSERT INTO Airlines VALUES ('MCA Airlines','MCA','Sweden')")
c.execute("INSERT INTO Airlines VALUES ('Maldivo Airlines','MAV','Maldives')")
c.execute("INSERT INTO Airlines VALUES ('Virgin Pacific','VNP','Fiji')")
c.execute("INSERT INTO Airlines VALUES ('Eastar Jet','ESR','South Korea')")
c.execute("INSERT INTO Airlines VALUES ('Jin Air','JNA','South Korea')")
c.execute("INSERT INTO Airlines VALUES ('Wataniya Airways','KW1','Kuwait')")
c.execute("INSERT INTO Airlines VALUES ('Baltic Air lines','BA1','Latvia')")
c.execute("INSERT INTO Airlines VALUES ('Ciel Canadien','YCC','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Canadian National Airways','YCP','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Epic Holiday','4AA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Indochina Airlines','AXC','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('German Air Force - FLB','FLB','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Line Blue','LBL','Germany')")
c.execute("INSERT INTO Airlines VALUES ('FlyLAL Charters','LLC','Lithuania')")
c.execute("INSERT INTO Airlines VALUES ('Texas Wings','TXW','United States')")
c.execute("INSERT INTO Airlines VALUES ('Dennis Sky','DSY','Israel')")
c.execute("INSERT INTO Airlines VALUES ('Atifly','A1F','United States')")
c.execute("INSERT INTO Airlines VALUES ('Aerolineas heredas santa maria','SZB','Dominican Republic')")
c.execute("INSERT INTO Airlines VALUES ('Jc royal.britannica','JRB','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('CanXpress','CA1','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Sharp Airlines','SHA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('CanXplorer','CAP','Canada')")
c.execute("INSERT INTO Airlines VALUES ('World Experience Airline','WE1','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Tianjin Airlines','GCR','China')")
c.execute("INSERT INTO Airlines VALUES ('Locair','LOC','United States')")
c.execute("INSERT INTO Airlines VALUES ('SeaPort Airlines','SQH','United States')")
c.execute("INSERT INTO Airlines VALUES ('Star1 Airlines','HCW','Lithuania')")
c.execute("INSERT INTO Airlines VALUES ('Enerjet','ENJ','Canada')")
c.execute("INSERT INTO Airlines VALUES ('MexicanaLink','MXI','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('Island Spirit','ISX','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Orbest','OBS','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Southern Air Charter','SOA','Bahamas')")
c.execute("INSERT INTO Airlines VALUES ('SVG Air','SVG','Saint Vincent and the Grenadines')")
c.execute("INSERT INTO Airlines VALUES ('Air Century','CEY','Dominican Republic')")
c.execute("INSERT INTO Airlines VALUES ('Sol Lineas Aereas','OLS','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Regional Paraguaya','REP','Paraguay')")
c.execute("INSERT INTO Airlines VALUES ('Transportes Aereos Cielos Andinos','NDN','Peru')")
c.execute("INSERT INTO Airlines VALUES ('EasyFly','EFY','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Andalus Lineas Aereas','ANU','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Air 26','DCD','Angola')")
c.execute("INSERT INTO Airlines VALUES ('Mauritania Airways','MTW','Mauritania')")
c.execute("INSERT INTO Airlines VALUES ('CEIBA Intercontinental','CEL','Equatorial Guinea')")
c.execute("INSERT INTO Airlines VALUES ('AlMasria Universal Airlines','LMU','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('EgyptAir Express','MSE','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Air Italy Egypt','EUD','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('KoralBlue Airlines','KBR','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Wind Rose Aviation','WRC','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Elysian Airlines','GIE','Cameroon')")
c.execute("INSERT INTO Airlines VALUES ('Sevenair','SEN','Tunisia')")
c.execute("INSERT INTO Airlines VALUES ('Hellenic Imperial Airways','IMP','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Amsterdam Airlines','AAN','Netherlands')")
c.execute("INSERT INTO Airlines VALUES ('Arik Niger','NAK','Niger')")
c.execute("INSERT INTO Airlines VALUES ('STP Airways','STP','Sao Tome and Principe')")
c.execute("INSERT INTO Airlines VALUES ('Skyjet Airlines','SJU','Uganda')")
c.execute("INSERT INTO Airlines VALUES ('Transavia Denmark','TDK','Denmark')")
c.execute("INSERT INTO Airlines VALUES ('Royal Falcon','RFJ','Jordan')")
c.execute("INSERT INTO Airlines VALUES ('Euroline','MJX','Georgia')")
c.execute("INSERT INTO Airlines VALUES ('Turkuaz Airlines','TRK','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Viking Hellas','VKH','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Norlandair','FNA','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Flugfelag Vestmannaeyja','FVM','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Gadair European Airlines','GDR','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Spirit of Manila Airlines','MNP','Philippines')")
c.execute("INSERT INTO Airlines VALUES ('Chongqing Airlines','CQN','China')")
c.execute("INSERT INTO Airlines VALUES ('Grand China Air','GDC','China')")
c.execute("INSERT INTO Airlines VALUES ('West Air China','CHB','China')")
c.execute("INSERT INTO Airlines VALUES ('QatXpress','QAX','Qatar')")
c.execute("INSERT INTO Airlines VALUES ('OneChina','1CH','China')")
c.execute("INSERT INTO Airlines VALUES ('Joy Air','JOY','China')")
c.execute("INSERT INTO Airlines VALUES ('Jagson Airlines','JGN','India')")
c.execute("INSERT INTO Airlines VALUES ('Fars Air Qeshm','QFZ','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Eastok Avia','EAA','Kyrgyzstan')")
c.execute("INSERT INTO Airlines VALUES ('Jupiter Airlines','JPU','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Vision Air International','VIS','Pakistan')")
c.execute("INSERT INTO Airlines VALUES ('Korea Express Air','KEA','South Korea')")
c.execute("INSERT INTO Airlines VALUES ('Eznis Airways','EZA','Mongolia')")
c.execute("INSERT INTO Airlines VALUES ('Pacific Flier','PFL','Palau')")
c.execute("INSERT INTO Airlines VALUES ('Syrian Pearl Airlines','PSB','Syria')")
c.execute("INSERT INTO Airlines VALUES ('Parmiss Airlines (IPV)','IPV','Iran')")
c.execute("INSERT INTO Airlines VALUES ('EuropeSky','EUV','Germany')")
c.execute("INSERT INTO Airlines VALUES ('BRAZIL AIR','BZE','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Homer Air','OME','Germany')")
c.execute("INSERT INTO Airlines VALUES ('U.S. Air','--+','United States')")
c.execute("INSERT INTO Airlines VALUES ('PanAm World Airways','PQW','United States')")
c.execute("INSERT INTO Airlines VALUES ('Virginwings','VWA','Germany')")
c.execute("INSERT INTO Airlines VALUES ('KSY','KSY','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Buquebus Líneas Aéreas','BQB','Uruguay')")
c.execute("INSERT INTO Airlines VALUES ('SOCHI AIR','KOL','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Wizz Air Ukraine','WAU','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('88','VVN','Cyprus')")
c.execute("INSERT INTO Airlines VALUES ('LCM AIRLINES','LMM','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Azul','AZU','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('LSM Airlines','LOO','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Zapolyarie Airlines','PZY','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Finlandian','FN1','Finland')")
c.execute("INSERT INTO Airlines VALUES ('LionXpress','LIX','Cameroon')")
c.execute("INSERT INTO Airlines VALUES ('Fly Dubai','FDB','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('Domenican Airlines','MDO','Dominican Republic')")
c.execute("INSERT INTO Airlines VALUES ('ConneX European Airline','2CO','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Aereonautica militare','AXZ','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Kal Star Aviation','KLS','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('LSM AIRLINES ','YZZ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Zabaykalskii Airlines','ZZZ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('CBM America','XBM','United States')")
c.execute("INSERT INTO Airlines VALUES ('Marysya Airlines','1QA','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Westfalia Express VA','WFX','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Black Stallion Airways','BSA','United States')")
c.execute("INSERT INTO Airlines VALUES ('German International Air Lines','GER','Germany')")
c.execute("INSERT INTO Airlines VALUES ('TrasBrasil','TBZ','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('TransBrasil Airlines','THS','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('AIR INDOCHINE','IIA','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('Happy Air','HPY','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Solar Air','SRB','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Air Mekong','MKG','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('Air Hamburg (AHO)','AHO','Germany')")
c.execute("INSERT INTO Airlines VALUES ('ZABAIKAL AIRLINES','ZTT','Russia')")
c.execute("INSERT INTO Airlines VALUES ('TransHolding','THI','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('SUR Lineas Aereas','SZZ','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Aerolineas Africanas','AA1','Guinea')")
c.execute("INSERT INTO Airlines VALUES ('Serbian Airlines','SA1','Serbia')")
c.execute("INSERT INTO Airlines VALUES ('TransHolding System','TYS','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('CCML Airlines','CCC','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Small Planet Airlines','ELC','Lithuania')")
c.execute("INSERT INTO Airlines VALUES ('Fly Brasil','FBL','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('CB Airways UK ( Interliging Flights )','CIF','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Fly Colombia ( Interliging Flights )','3FF','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Trans Pas Air','TP6','United States')")
c.execute("INSERT INTO Airlines VALUES ('Himalayan Airlines','HYM','Nepal')")
c.execute("INSERT INTO Airlines VALUES ('Indya Airline Group','IG1','India')")
c.execute("INSERT INTO Airlines VALUES ('Turkish Wings Domestic','TWD','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Japan Regio','ZXY','Japan')")
c.execute("INSERT INTO Airlines VALUES ('OCEAN AIR CARGO','IXO','India')")
c.execute("INSERT INTO Airlines VALUES ('Nihon.jet connect','NX1','Kyrgyzstan')")
c.execute("INSERT INTO Airlines VALUES ('Sky Regional','SKV','Canada')")
c.execute("INSERT INTO Airlines VALUES ('LSM International ','UWW','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Baikotovitchestrian Airlines ','BUU','American Samoa')")
c.execute("INSERT INTO Airlines VALUES ('Luchsh Airlines ','LJJ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('ENTERair','QQQ','Poland')")
c.execute("INSERT INTO Airlines VALUES ('Mongolian International Air Lines ','ZTF','Mongolia')")
c.execute("INSERT INTO Airlines VALUES ('Tway Airlines','TWB','South Korea')")
c.execute("INSERT INTO Airlines VALUES ('Jusur airways','JSR','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('NEXT Brasil','NXB','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('AeroWorld ','WER','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Usa Sky Cargo','ES2','United States')")
c.execute("INSERT INTO Airlines VALUES ('Hankook Airline','HNX','South Korea')")
c.execute("INSERT INTO Airlines VALUES ('Sprintair','SRN','Poland')")
c.execute("INSERT INTO Airlines VALUES ('Marusya Airways','MRS','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Era Alaska','ERR','United States')")
c.execute("INSERT INTO Airlines VALUES ('AirRussia','RRJ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Hankook Air US','HA1','United States')")
c.execute("INSERT INTO Airlines VALUES ('Carpatair Flight Training','SMW','Romania')")
c.execute("INSERT INTO Airlines VALUES ('I-Fly','RSY','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Whitejets','WTJ','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('VickJet','VKJ','France')")
c.execute("INSERT INTO Airlines VALUES ('Hamburg Airways','HAY','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Kan Air','KND','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Air Cudlua','CUD','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Air Explore','AXE','Slovakia')")
c.execute("INSERT INTO Airlines VALUES ('12 North','N12','India')")
c.execute("INSERT INTO Airlines VALUES ('Holidays Czech Airlines','HCC','Czech Republic')")
c.execute("INSERT INTO Airlines VALUES ('Comtel Air','COE','Austria')")
c.execute("INSERT INTO Airlines VALUES ('Mint Airways','MIC','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Orbit Airlines','OBT','United States')")
c.execute("INSERT INTO Airlines VALUES ('Air Bucharest','BUR','Romania')")
c.execute("INSERT INTO Airlines VALUES ('AlbaStar','LAV','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Mauritania Airlines International','MAI','Mauritania')")
c.execute("INSERT INTO Airlines VALUES ('MAT Airways','MKD','Macedonia')")
c.execute("INSERT INTO Airlines VALUES ('Asian Wings Airways','AWM','Burma')")
c.execute("INSERT INTO Airlines VALUES ('Air Arabia Egypt','RBG','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Eagles Airlines','EGS','Italy')")
c.execute("INSERT INTO Airlines VALUES ('YES Airways','YEP','Poland')")
c.execute("INSERT INTO Airlines VALUES ('Direct Aero Services','DSV','Romania')")
c.execute("INSERT INTO Airlines VALUES ('Medallion Air','MDP','Romania')")
c.execute("INSERT INTO Airlines VALUES ('Orchid Airlines','ORC','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Asia Wings','AWA','Kazakhstan')")
c.execute("INSERT INTO Airlines VALUES ('Georgian International Airlines','GNN','Georgia')")
c.execute("INSERT INTO Airlines VALUES ('Air Batumi','BTM','Georgia')")
c.execute("INSERT INTO Airlines VALUES ('Nile Air','NIA','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('Feeder Airlines','FDD','Sudan')")
c.execute("INSERT INTO Airlines VALUES ('Senegal Airlines','SGG','Senegal')")
c.execute("INSERT INTO Airlines VALUES ('Copenhagen Express','CX0','Denmark')")
c.execute("INSERT INTO Airlines VALUES ('BusinessAir','BCC','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('XOJET','XOJ','United States')")
c.execute("INSERT INTO Airlines VALUES ('Sky Wing Pacific','CR7','South Korea')")
c.execute("INSERT INTO Airlines VALUES ('Bateleur Air','BEU','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Air Indus','AI0','Pakistan')")
c.execute("INSERT INTO Airlines VALUES ('Orbit International Airlines','OAI','United States')")
c.execute("INSERT INTO Airlines VALUES ('Orbit Regional Airlines','OAR','United States')")
c.execute("INSERT INTO Airlines VALUES ('Orbit Atlantic Airways','OAN','United States')")
c.execute("INSERT INTO Airlines VALUES ('Volotea','VOO','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Helitt Líneas Aéreas','HTH','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Russia State Transport','RSD','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Malaysia Wings','MWI','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('Aviabus','ABI','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Michael Airlines','MJG','Puerto Rico')")
c.execute("INSERT INTO Airlines VALUES ('Korongo Airlines','KGO','Congo (Kinshasa)')")
c.execute("INSERT INTO Airlines VALUES ('Indonesia Sky','IDS','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Aws express','666','United States')")
c.execute("INSERT INTO Airlines VALUES ('Southjet','SJS','United States')")
c.execute("INSERT INTO Airlines VALUES ('Southjet connect','ZCS','United States')")
c.execute("INSERT INTO Airlines VALUES ('Southjet cargo','XAN','United States')")
c.execute("INSERT INTO Airlines VALUES ('Iberia Express','IBS','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Nordic Global Airlines','NGB','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Scoot','SCO','Singapore')")
c.execute("INSERT INTO Airlines VALUES ('Zenith International Airline','ZNA','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Orbit Airlines Azerbaijan','OAB','Azerbaijan')")
c.execute("INSERT INTO Airlines VALUES ('Flying kangaroo Airline','FKA','Australia')")
c.execute("INSERT INTO Airlines VALUES ('RusJet','RSJ','Russia')")
c.execute("INSERT INTO Airlines VALUES ('VietJet Air','VJC','Vietnam')")
c.execute("INSERT INTO Airlines VALUES ('Vision Airlines (V2)','RBY','United States')")
c.execute("INSERT INTO Airlines VALUES ('AirAsia Japan','WAJ','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Yellowtail','YEL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Royal Airways','RAW','United States')")
c.execute("INSERT INTO Airlines VALUES ('FlyHigh Airlines Ireland (FH)','FHI','Ireland')")
c.execute("INSERT INTO Airlines VALUES ('Executive AirShare','XSR','United States')")
c.execute("INSERT INTO Airlines VALUES ('Hebei Airlines','HBH','China')")
c.execute("INSERT INTO Airlines VALUES ('Air KBZ','KBZ','Burma')")
c.execute("INSERT INTO Airlines VALUES ('T.J. Air','TJA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Ukraine Atlantic','UAT','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Nesma Airlines','NMA','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('East Horizon','EHN','Afghanistan')")
c.execute("INSERT INTO Airlines VALUES ('Air Majoro','MJP','Peru')")
c.execute("INSERT INTO Airlines VALUES ('Rotana Jet','RJD','United Arab Emirates')")
c.execute("INSERT INTO Airlines VALUES ('SOCHI AIR CHATER','QER','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Malindo Air','MXD','Malaysia')")
c.execute("INSERT INTO Airlines VALUES ('Hermes Airlines','HRM','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Катэкавиа','КТК','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Псковавиа','PKV','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Maryland Air','M1F','United States')")
c.execute("INSERT INTO Airlines VALUES ('VivaColombia','VVC','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Flybe Finland Oy','FCM','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Bingo Airways','BGY','Poland')")
c.execute("INSERT INTO Airlines VALUES ('Bluebird Airways (BZ)','BBG','Greece')")
c.execute("INSERT INTO Airlines VALUES ('Apache Air','IWA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Jettor Airlines','JTO','Hong Kong')")
c.execute("INSERT INTO Airlines VALUES ('Flyme (VP)','VQI','Maldives')")
c.execute("INSERT INTO Airlines VALUES ('Golden Myanmar Airlines','GMR','Burma')")
c.execute("INSERT INTO Airlines VALUES ('Canaryfly','CNF','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Sunrise Airways','KSZ','Haiti')")
c.execute("INSERT INTO Airlines VALUES ('National Air Cargo','NCR','United States')")
c.execute("INSERT INTO Airlines VALUES ('Eastern Atlantic Virtual Airlines','EAV','United States')")
c.execute("INSERT INTO Airlines VALUES ('Transair','TTZ','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Comfort Express Virtual Charters Albany','EVC','United States')")
c.execute("INSERT INTO Airlines VALUES ('Comfort Express Virtual Charters','CEO','United States')")
c.execute("INSERT INTO Airlines VALUES ('FLYJET','FYJ','Poland')")
c.execute("INSERT INTO Airlines VALUES ('Snowbird Airlines','SBD','Finland')")
c.execute("INSERT INTO Airlines VALUES ('Russkie Krylya','KRY','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Kharkiv Airlines','KHK','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('XAIR USA','XAU','United States')")
c.execute("INSERT INTO Airlines VALUES ('Simrik Airlines','RMK','Nepal')")
c.execute("INSERT INTO Airlines VALUES ('XPTO','XPT','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Royal Flight','DME','Russia')")
c.execute("INSERT INTO Airlines VALUES ('BBN-Airways','EGH','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Tomsk-Avia','TKS','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Yeti Airlines ','NYT','Nepal')")
c.execute("INSERT INTO Airlines VALUES ('Avilu','...','Switzerland')")
c.execute("INSERT INTO Airlines VALUES ('Air Serbia','ASL','Serbia')")
c.execute("INSERT INTO Airlines VALUES ('Skyline Ulasim Ticaret A.S.','KCU','Turkey')")
c.execute("INSERT INTO Airlines VALUES ('Air Lituanica','LTU','Lithuania')")
c.execute("INSERT INTO Airlines VALUES ('Envoy Air','ENY','United States')")
c.execute("INSERT INTO Airlines VALUES ('CARICOM AIRWAYS (BARBADOS) INC.','CCB','Barbados')")
c.execute("INSERT INTO Airlines VALUES ('Rainbow Air (RAI)','RAB','United States')")
c.execute("INSERT INTO Airlines VALUES ('Rainbow Air Canada','RAY','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Rainbow Air Polynesia','RPO','United States')")
c.execute("INSERT INTO Airlines VALUES ('Rainbow Air Euro','RUE','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Rainbow Air US','RNY','United States')")
c.execute("INSERT INTO Airlines VALUES ('Transilvania','TNS','Romania')")
c.execute("INSERT INTO Airlines VALUES ('Dobrolet','DOB','Russia')")
c.execute("INSERT INTO Airlines VALUES ('Spike Airlines','SAL','United States')")
c.execute("INSERT INTO Airlines VALUES ('Grand Cru Airlines','GCA','Lithuania')")
c.execute("INSERT INTO Airlines VALUES ('Go2Sky','RLX','Slovakia')")
c.execute("INSERT INTO Airlines VALUES ('All Argentina','AL1','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('All America','AL2','United States')")
c.execute("INSERT INTO Airlines VALUES ('All Asia','AL3','China')")
c.execute("INSERT INTO Airlines VALUES ('All Africa','99F','South Africa')")
c.execute("INSERT INTO Airlines VALUES ('Regionalia México','J88','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('All Europe','N99','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('All Spain','N77','Spain')")
c.execute("INSERT INTO Airlines VALUES ('Regional Air Iceland','N78','Iceland')")
c.execute("INSERT INTO Airlines VALUES ('Voestar','K88','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('All Colombia','7KK','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('Regionalia Uruguay','2K2','Uruguay')")
c.execute("INSERT INTO Airlines VALUES ('Regionalia Venezuela','9XX','Venezuela')")
c.execute("INSERT INTO Airlines VALUES ('Regionalia Chile','CR1','Chile')")
c.execute("INSERT INTO Airlines VALUES ('Vuela Cuba','6CC','Cuba')")
c.execute("INSERT INTO Airlines VALUES ('All Australia','8K8','Australia')")
c.execute("INSERT INTO Airlines VALUES ('Fly Europa','RWW','Spain')")
c.execute("INSERT INTO Airlines VALUES ('FlyPortugal','FPT','Portugal')")
c.execute("INSERT INTO Airlines VALUES ('Spring Airlines Japan','SJO','Japan')")
c.execute("INSERT INTO Airlines VALUES ('Dense Airways','DWA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Dense Connection','DC2','United States')")
c.execute("INSERT INTO Airlines VALUES ('Vuola Italia','VI4','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Jet Suite','RSP','United States')")
c.execute("INSERT INTO Airlines VALUES ('Fly Jamaica Airways','FJM','Jamaica')")
c.execute("INSERT INTO Airlines VALUES ('All Argentina Express','Z9H','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('All America AR','M7A','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('All America CL','R1R','Chile')")
c.execute("INSERT INTO Airlines VALUES ('SOCHI AIR EXPRESS','SAE','Russia')")
c.execute("INSERT INTO Airlines VALUES ('All America BR','A9B','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Volotea Costa Rica','VC9','Costa Rica')")
c.execute("INSERT INTO Airlines VALUES ('Fly Romania','OTJ','Romania')")
c.execute("INSERT INTO Airlines VALUES ('Fly Africa Zimbabwe','FZW','Zimbabwe')")
c.execute("INSERT INTO Airlines VALUES ('San Dima Air','SDI','United States')")
c.execute("INSERT INTO Airlines VALUES ('All America CO','7ZC','Colombia')")
c.execute("INSERT INTO Airlines VALUES ('All America MX','0MM','Mexico')")
c.execute("INSERT INTO Airlines VALUES ('FOX Linhas Aereas','FOX','Brazil')")
c.execute("INSERT INTO Airlines VALUES ('Via Conectia Airlines','CZV','Uruguay')")
c.execute("INSERT INTO Airlines VALUES ('Hebradran Air Services','HBR','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Pobeda','PBD','Russia')")
c.execute("INSERT INTO Airlines VALUES ('City Airways','GTA','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('Norwegian Long Haul AS','NLH','Norway')")
c.execute("INSERT INTO Airlines VALUES ('BA101','710','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('TransNusa Air','TNU','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Tomp Airlines','T9P','Chile')")
c.execute("INSERT INTO Airlines VALUES ('Fuzhou Airlines','FZA','China')")
c.execute("INSERT INTO Airlines VALUES ('Sky Angkor Airlines (ZA)','SWM','Cambodia')")
c.execute("INSERT INTO Airlines VALUES ('Global Airlines','GA0','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Mann Yadanarpon Airlines','MYP','Burma')")
c.execute("INSERT INTO Airlines VALUES ('Air Vistara','VTI','India')")
c.execute("INSERT INTO Airlines VALUES ('TransRussiaAirlines','RGG','Russia')")
c.execute("INSERT INTO Airlines VALUES ('REXAIR VIRTUEL','RXR','France')")
c.execute("INSERT INTO Airlines VALUES ('WestJet Encore','WEN','Canada')")
c.execute("INSERT INTO Airlines VALUES ('Air Pegasus','PPL','India')")
c.execute("INSERT INTO Airlines VALUES ('International Europe','INE','Spain')")
c.execute("INSERT INTO Airlines VALUES ('V Air','VAX','Taiwan')")
c.execute("INSERT INTO Airlines VALUES ('Cello Aviation','CLJ','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Pouya Air','PYA','Iran')")
c.execute("INSERT INTO Airlines VALUES ('Boutique Air (Priv)','BTQ','United States')")
c.execute("INSERT INTO Airlines VALUES ('FlyEgypt','FEG','Egypt')")
c.execute("INSERT INTO Airlines VALUES ('VOLOTEA Airways','VOE','Spain')")
c.execute("INSERT INTO Airlines VALUES ('INAVIA Internacional','IIR','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('Liberty Airways','LTY','United States')")
c.execute("INSERT INTO Airlines VALUES ('Aeronautica Militare','IAM','Italy')")
c.execute("INSERT INTO Airlines VALUES ('Bassaka airlines','BSX','Cambodia')")
c.execute("INSERT INTO Airlines VALUES ('Jetstar Japan ','JJP','Japan')")
c.execute("INSERT INTO Airlines VALUES ('First Flying','DAK','Japan')")
c.execute("INSERT INTO Airlines VALUES ('AtlasGlobal Ukraine','UJX','Ukraine')")
c.execute("INSERT INTO Airlines VALUES ('Boliviana de Aviacion (OB)','BOV','Bolivia')")
c.execute("INSERT INTO Airlines VALUES ('US-Bangla Airlines','UBG','Bangladesh')")
c.execute("INSERT INTO Airlines VALUES ('Norwegian Air International (D8)','IBK','Norway')")
c.execute("INSERT INTO Airlines VALUES ('VIA Líneas Aéreas','VIA','Argentina')")
c.execute("INSERT INTO Airlines VALUES ('GermanXL','GXG','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Alghanim','KYA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Indonesa Air Aisa X','IDX','Indonesia')")
c.execute("INSERT INTO Airlines VALUES ('Fly France','FRF','France')")
c.execute("INSERT INTO Airlines VALUES ('Jota Aviation','ENZ','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Europe Jet','EU9','France')")
c.execute("INSERT INTO Airlines VALUES ('COBALT','FCB','Cyprus')")
c.execute("INSERT INTO Airlines VALUES ('Southern Airways Express','LTD','United States')")
c.execute("INSERT INTO Airlines VALUES ('Orenburzhie','ORG','Russia')")
c.execute("INSERT INTO Airlines VALUES ('World Scale Airlines','WSS','United States')")
c.execute("INSERT INTO Airlines VALUES ('All America US','SSA','United States')")
c.execute("INSERT INTO Airlines VALUES ('University of Birmingham Air Squadron (RAF)','UAY','United Kingdom')")
c.execute("INSERT INTO Airlines VALUES ('Choice Airways','CSX','United States')")
c.execute("INSERT INTO Airlines VALUES ('Aruba Airlines','ARU','Aruba')")
c.execute("INSERT INTO Airlines VALUES ('BudgetAir','BG1','Germany')")
c.execute("INSERT INTO Airlines VALUES ('Dynamic Airways','DYA','United States')")
c.execute("INSERT INTO Airlines VALUES ('Fly One','FI5','Moldova')")
c.execute("INSERT INTO Airlines VALUES ('Tez Jet Airlines','TEZ','Kyrgyzstan')")
c.execute("INSERT INTO Airlines VALUES ('Kush Air','KUH','South Sudan')")
c.execute("INSERT INTO Airlines VALUES ('ViaAir','SRY','United States')")
c.execute("INSERT INTO Airlines VALUES ('All America BOPY','PYB','Paraguay')")
c.execute("INSERT INTO Airlines VALUES ('Thai Vietjet Air','TVJ','Thailand')")
c.execute("INSERT INTO Airlines VALUES ('GX Airlines','CBG','China')")



conn.commit()




conn.close()